In [2]:
import pandas as pd
import numpy as np
import os

# =========================
# Load cleaned files
# =========================

train_path = "../MLOpsedian/data/processed/train_cleaned.csv"
test_path = "../MLOpsedian/data/processed/test_cleaned.csv"

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

id_col = "record_id"
target = "flood_risk_score"

print("Original train shape:", train.shape)
print("Original test shape:", test.shape)

print("\nOriginal missing values:")
print("Train missing:", train.isnull().sum().sum())
print("Test missing:", test.isnull().sum().sum())

print("\nRows with any missing in train:", train.isnull().any(axis=1).sum())
print("Rows without missing in train:", (~train.isnull().any(axis=1)).sum())


# =========================
# VERSION 1: Drop missing rows only
# =========================

train_dropmissing = train.dropna().copy()
test_dropmissing = test.copy()

print("\n==============================")
print("VERSION 1: DROP MISSING ONLY")
print("==============================")
print("Train shape:", train_dropmissing.shape)
print("Test shape:", test_dropmissing.shape)
print("Train missing:", train_dropmissing.isnull().sum().sum())
print("Test missing:", test_dropmissing.isnull().sum().sum())
print("Duplicate train IDs:", train_dropmissing[id_col].duplicated().sum())
print("Duplicate test IDs:", test_dropmissing[id_col].duplicated().sum())
print("Train-only columns:", set(train_dropmissing.columns) - set(test_dropmissing.columns))
print("Test-only columns:", set(test_dropmissing.columns) - set(train_dropmissing.columns))


# =========================
# VERSION 2: Drop missing + invalid rows
# =========================

invalid_rules = {
    "distance_to_river_m": {"min": 0, "max": None},
    "rainfall_7d_mm": {"min": 0, "max": None},
    "monthly_rainfall_mm": {"min": 0, "max": None},
    "built_up_percent": {"min": 0, "max": 100},
    "drainage_index": {"min": 0, "max": 1},
    "ndvi": {"min": -1, "max": 1},
    "ndwi": {"min": -1, "max": 1},
    "elevation_m": {"min": 0, "max": None}
}

missing_mask = train.isnull().any(axis=1)
invalid_mask = pd.Series(False, index=train.index)

invalid_report = []

for col, rule in invalid_rules.items():
    if col in train.columns:
        col_invalid = pd.Series(False, index=train.index)
        
        if rule["min"] is not None:
            col_invalid |= train[col] < rule["min"]
        
        if rule["max"] is not None:
            col_invalid |= train[col] > rule["max"]
        
        col_invalid = col_invalid.fillna(False)
        invalid_mask |= col_invalid
        
        invalid_report.append({
            "column": col,
            "invalid_count": int(col_invalid.sum()),
            "min_value": train[col].min(),
            "max_value": train[col].max()
        })

invalid_report_df = pd.DataFrame(invalid_report)

train_dropmissing_invalid = train.loc[~(missing_mask | invalid_mask)].copy()
test_dropmissing_invalid = test.copy()

print("\n==============================")
print("VERSION 2: DROP MISSING + INVALID")
print("==============================")
print("Rows with missing:", int(missing_mask.sum()))
print("Rows with invalid values:", int(invalid_mask.sum()))
print("Rows with missing OR invalid:", int((missing_mask | invalid_mask).sum()))
print("Rows kept:", train_dropmissing_invalid.shape[0])

print("\nTrain shape:", train_dropmissing_invalid.shape)
print("Test shape:", test_dropmissing_invalid.shape)
print("Train missing:", train_dropmissing_invalid.isnull().sum().sum())
print("Test missing:", test_dropmissing_invalid.isnull().sum().sum())
print("Duplicate train IDs:", train_dropmissing_invalid[id_col].duplicated().sum())
print("Duplicate test IDs:", test_dropmissing_invalid[id_col].duplicated().sum())
print("Train-only columns:", set(train_dropmissing_invalid.columns) - set(test_dropmissing_invalid.columns))
print("Test-only columns:", set(test_dropmissing_invalid.columns) - set(train_dropmissing_invalid.columns))

print("\nInvalid value report:")
display(invalid_report_df)


# =========================
# Check target balance
# =========================

def target_balance(df, name):
    bins = pd.cut(
        df[target],
        bins=[-0.001, 0.2, 0.4, 0.6, 0.8, 1.001],
        labels=[
            "0.0-0.2 very low",
            "0.2-0.4 low",
            "0.4-0.6 medium",
            "0.6-0.8 high",
            "0.8-1.0 very high"
        ]
    )
    
    report = pd.DataFrame({
        "count": bins.value_counts().sort_index(),
        "percentage": (bins.value_counts(normalize=True).sort_index() * 100).round(2)
    })
    
    print("\n==============================")
    print(name)
    print("==============================")
    print("Shape:", df.shape)
    print(report)
    
    return report

balance_full = target_balance(train, "Original cleaned train")
balance_dropmissing = target_balance(train_dropmissing, "Drop missing train")
balance_strict = target_balance(train_dropmissing_invalid, "Drop missing + invalid train")


# =========================
# Save files
# =========================

os.makedirs("../MLOpsedian/data/processed", exist_ok=True)
os.makedirs("../MLOpsedian/reports", exist_ok=True)

train_dropmissing.to_csv("../MLOpsedian/data/processed/train_dropmissing.csv", index=False)
test_dropmissing.to_csv("../MLOpsedian/data/processed/test_dropmissing.csv", index=False)

train_dropmissing_invalid.to_csv("../MLOpsedian/data/processed/train_dropmissing_invalid.csv", index=False)
test_dropmissing_invalid.to_csv("../MLOpsedian/data/processed/test_dropmissing_invalid.csv", index=False)

invalid_report_df.to_csv("../MLOpsedian/reports/invalid_rows_removed_report.csv", index=False)
balance_full.to_csv("../MLOpsedian/reports/balance_original_cleaned_train.csv")
balance_dropmissing.to_csv("../MLOpsedian/reports/balance_dropmissing_train.csv")
balance_strict.to_csv("../MLOpsedian/reports/balance_dropmissing_invalid_train.csv")

print("\n==============================")
print("FILES SAVED")
print("==============================")
print("../MLOpsedian/data/processed/train_dropmissing.csv")
print("../MLOpsedian/data/processed/test_dropmissing.csv")
print("../MLOpsedian/data/processed/train_dropmissing_invalid.csv")
print("../MLOpsedian/data/processed/test_dropmissing_invalid.csv")
print("../MLOpsedian/reports/invalid_rows_removed_report.csv")

Original train shape: (19700, 69)
Original test shape: (5300, 68)

Original missing values:
Train missing: 32761
Test missing: 0

Rows with any missing in train: 4182
Rows without missing in train: 15518

==============================
VERSION 1: DROP MISSING ONLY
==============================
Train shape: (15518, 69)
Test shape: (5300, 68)
Train missing: 0
Test missing: 0
Duplicate train IDs: 0
Duplicate test IDs: 0
Train-only columns: {'flood_risk_score'}
Test-only columns: set()

==============================
VERSION 2: DROP MISSING + INVALID
==============================
Rows with missing: 4182
Rows with invalid values: 683
Rows with missing OR invalid: 4779
Rows kept: 14921

Train shape: (14921, 69)
Test shape: (5300, 68)
Train missing: 0
Test missing: 0
Duplicate train IDs: 0
Duplicate test IDs: 0
Train-only columns: {'flood_risk_score'}
Test-only columns: set()

Invalid value report:

                column  invalid_count   min_value     max_value
0  distance_to_river_m            117 -485.397750  16802.000000
1       rainfall_7d_mm             96  -49.199358    914.823318
2  monthly_rainfall_mm             96  -79.170571   2032.274155
3     built_up_percent             72    1.000000    178.263721
4       drainage_index             71    0.003000      1.779877
5                 ndvi             71   -0.792000      1.595039
6                 ndwi             71   -1.000000      1.596308
7          elevation_m             97  -79.564149   2148.000000

==============================
Original cleaned train
==============================
Shape: (19700, 69)
                   count  percentage
flood_risk_score
0.0-0.2 very low    2390       12.13
0.2-0.4 low         4402       22.35
0.4-0.6 medium      7650       38.83
0.6-0.8 high        3353       17.02
0.8-1.0 very high   1905        9.67

==============================
Drop missing train
==============================
Shape: (15518, 69)
                   count  percentage
flood_risk_score
0.0-0.2 very low    1899       12.24
0.2-0.4 low         3455       22.26
0.4-0.6 medium      5993       38.62
0.6-0.8 high        2655       17.11
0.8-1.0 very high   1516        9.77

==============================
Drop missing + invalid train
==============================
Shape: (14921, 69)
                   count  percentage
flood_risk_score
0.0-0.2 very low    1816       12.17
0.2-0.4 low         3338       22.37
0.4-0.6 medium      5757       38.58
0.6-0.8 high        2561       17.16
0.8-1.0 very high   1449        9.71

==============================
FILES SAVED
==============================
../MLOpsedian/data/processed/train_dropmissing.csv
../MLOpsedian/data/processed/test_dropmissing.csv
../MLOpsedian/data/processed/train_dropmissing_invalid.csv
../MLOpsedian/data/processed/test_dropmissing_invalid.csv
../MLOpsedian/reports/invalid_rows_removed_report.csv

In [3]:
# ============================================================
# CatBoost Alpha Pack on Drop-Missing Dataset
# One-cell version
# ============================================================

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from catboost import CatBoostRegressor

# ============================================================
# 1. Load drop-missing datasets
# ============================================================

train_path = "../MLOpsedian/data/processed/train_dropmissing.csv"
test_path = "../MLOpsedian/data/processed/test_dropmissing.csv"

# Backup path in case your files are saved inside MLOpsedian folder


train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

id_col = "record_id"
target = "flood_risk_score"

print("Train path:", train_path)
print("Test path:", test_path)
print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Train missing:", train.isnull().sum().sum())
print("Test missing:", test.isnull().sum().sum())
print("Duplicate train IDs:", train[id_col].duplicated().sum())
print("Duplicate test IDs:", test[id_col].duplicated().sum())
print("Train-only columns:", set(train.columns) - set(test.columns))
print("Test-only columns:", set(test.columns) - set(train.columns))
print("Target valid:", train[target].between(0, 1).all())

# ============================================================
# 2. Add Alpha Pack engineered features
# ============================================================

def add_alpha_pack_features(df):
    df = df.copy()
    eps = 1e-5
    
    # Use clipped columns if available
    if "distance_to_river_m_clipped" in df.columns:
        distance = df["distance_to_river_m_clipped"]
    else:
        distance = df["distance_to_river_m"].clip(lower=0)
    
    if "rainfall_7d_mm_clipped" in df.columns:
        rainfall_7d = df["rainfall_7d_mm_clipped"]
    else:
        rainfall_7d = df["rainfall_7d_mm"].clip(lower=0)
    
    inundation = df["inundation_area_sqm"].clip(lower=0)
    
    # 1. Golden distance-rainfall ratio
    df["GOLDEN_distance_rainfall_ratio"] = (
        np.log1p(distance) - np.log1p(rainfall_7d + eps)
    )
    
    # 2. Flood spread ratio
    df["distance_to_river_DIV_inundation_area"] = (
        distance / (inundation + eps)
    )
    
    # 3. Water velocity proxy
    df["distance_to_river_DIV_rainfall_7d"] = (
        distance / (rainfall_7d + eps)
    )
    
    # 4. Water volume proxy
    df["rainfall_7d_MULT_inundation_area"] = (
        rainfall_7d * inundation
    )
    
    new_cols = [
        "GOLDEN_distance_rainfall_ratio",
        "distance_to_river_DIV_inundation_area",
        "distance_to_river_DIV_rainfall_7d",
        "rainfall_7d_MULT_inundation_area"
    ]
    
    for col in new_cols:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
        df[col] = df[col].fillna(df[col].median())
    
    return df

train_fe = add_alpha_pack_features(train)
test_fe = add_alpha_pack_features(test)

print("\nAfter feature engineering:")
print("Train shape:", train_fe.shape)
print("Test shape:", test_fe.shape)
print("Train missing:", train_fe.isnull().sum().sum())
print("Test missing:", test_fe.isnull().sum().sum())

# ============================================================
# 3. Define Alpha Pack features
# ============================================================

alpha_pack_features = [
    "district",
    "distance_to_river_DIV_inundation_area",
    "distance_to_river_DIV_rainfall_7d",
    "GOLDEN_distance_rainfall_ratio",
    "generation_date",
    "reason_not_good_to_live",
    "inundation_area_sqm",
    "infrastructure_score",
    "extreme_weather_index",
    "terrain_roughness_index",
    "road_quality",
    "monthly_rainfall_mm_log1p",
    "landcover",
    "rainfall_7d_MULT_inundation_area",
    "place_name",
    "rainfall_7d_mm",
    "seasonal_index",
    "ndwi_qmap",
    "latitude",
    "longitude",
    "distance_to_river_m",
    "ndwi",
    "water_supply",
    "nearest_evac_km_log1p",
    "elevation_m_yeojohnson",
    "monthly_rainfall_mm",
    "socioeconomic_status_index",
    "population_density_per_km2_log1p",
    "water_presence_flag",
    "nearest_hospital_km_log1p",
    "ndvi_qmap",
    "flood_occurrence_current_event",
    "rainfall_7d_mm_log1p",
    "soil_type",
    "population_density_per_km2"
]

missing_train_features = [col for col in alpha_pack_features if col not in train_fe.columns]
missing_test_features = [col for col in alpha_pack_features if col not in test_fe.columns]

print("\nFeature check:")
print("Number of alpha pack features:", len(alpha_pack_features))
print("Missing train features:", missing_train_features)
print("Missing test features:", missing_test_features)

if len(missing_train_features) > 0 or len(missing_test_features) > 0:
    raise ValueError("Some alpha pack features are missing. Stop and check columns.")

# ============================================================
# 4. Prepare X, y, X_test
# ============================================================

X = train_fe[alpha_pack_features].copy()
y = train_fe[target].copy()

X_test = test_fe[alpha_pack_features].copy()
test_ids = test_fe[id_col].copy()

print("\nModel data:")
print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)
print("Missing in X:", X.isnull().sum().sum())
print("Missing in X_test:", X_test.isnull().sum().sum())
print("Feature columns match:", list(X.columns) == list(X_test.columns))

# ============================================================
# 5. Identify categorical features
# ============================================================

cat_features = [
    col for col in X.columns
    if X[col].dtype == "object" or str(X[col].dtype) == "str"
]

print("\nCategorical features:")
print("Number of categorical features:", len(cat_features))
print(cat_features)

# ============================================================
# 6. Target bins for balance-aware StratifiedKFold
# ============================================================

target_bins = pd.cut(
    y,
    bins=[-0.001, 0.2, 0.4, 0.6, 0.8, 1.001],
    labels=[0, 1, 2, 3, 4]
)

print("\nTarget bin distribution:")
print(target_bins.value_counts().sort_index())

# ============================================================
# 7. Submission validation function
# ============================================================

def validate_submission(submission):
    print("\nSubmission shape:", submission.shape)
    print(submission.head())
    
    print("\nMissing values:")
    print(submission.isnull().sum())
    
    print("\nPrediction range:")
    print("Min:", submission["flood_risk_score"].min())
    print("Max:", submission["flood_risk_score"].max())
    
    assert submission.shape[0] == len(test_ids)
    assert list(submission.columns) == ["record_id", "flood_risk_score"]
    assert submission["flood_risk_score"].isnull().sum() == 0
    assert submission["flood_risk_score"].between(0, 1).all()
    
    print("\nSubmission is valid.")

# ============================================================
# 8. Train CatBoost Alpha Pack on drop-missing data
# ============================================================

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

rmse_scores = []
mae_scores = []
r2_scores = []

test_preds = np.zeros(len(X_test))

for fold, (train_idx, valid_idx) in enumerate(skf.split(X, target_bins), 1):
    print("\n" + "=" * 70)
    print(f"Fold {fold}")
    
    X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
    y_train, y_valid = y.iloc[train_idx], y.iloc[valid_idx]
    
    model = CatBoostRegressor(
        iterations=2000,
        learning_rate=0.03,
        depth=6,
        loss_function="RMSE",
        eval_metric="RMSE",
        random_seed=42 + fold,
        verbose=200,
        early_stopping_rounds=200,
        allow_writing_files=False
    )
    
    model.fit(
        X_train,
        y_train,
        cat_features=cat_features,
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )
    
    valid_preds = model.predict(X_valid)
    valid_preds = np.clip(valid_preds, 0, 1)
    
    rmse = np.sqrt(mean_squared_error(y_valid, valid_preds))
    mae = mean_absolute_error(y_valid, valid_preds)
    r2 = r2_score(y_valid, valid_preds)
    
    rmse_scores.append(rmse)
    mae_scores.append(mae)
    r2_scores.append(r2)
    
    print("Fold RMSE:", rmse)
    print("Fold MAE :", mae)
    print("Fold R²  :", r2)
    
    fold_test_preds = model.predict(X_test)
    test_preds += fold_test_preds / skf.n_splits

print("\n" + "=" * 70)
print("CatBoost Alpha Pack Drop-Missing CV Results")
print("Average RMSE:", np.mean(rmse_scores))
print("Average MAE :", np.mean(mae_scores))
print("Average R²  :", np.mean(r2_scores))

# ============================================================
# 9. Create submission
# ============================================================

dropmissing_preds = np.clip(test_preds, 0, 1)

print("\nPrediction distribution:")
print("Prediction min:", dropmissing_preds.min())
print("Prediction max:", dropmissing_preds.max())
print("Prediction mean:", dropmissing_preds.mean())
print("Prediction std:", dropmissing_preds.std())

sub_dropmissing = pd.DataFrame({
    "record_id": test_ids,
    "flood_risk_score": dropmissing_preds
})

validate_submission(sub_dropmissing)

os.makedirs("../submissions", exist_ok=True)

sub_dropmissing.to_csv(
    "../submissions/sub_v010_catboost_alpha_pack_dropmissing.csv",
    index=False
)

print("\nSaved: ../submissions/sub_v010_catboost_alpha_pack_dropmissing.csv")

# ============================================================
# 10. Compare with previous best
# ============================================================

comparison = pd.DataFrame([
    {
        "version": "sub_v008_catboost_alpha_pack",
        "dataset": "Full cleaned train",
        "rows": 19700,
        "cv_rmse": 0.23164778640435246,
        "cv_mae": 0.17673736118136243,
        "cv_r2": 0.03463008143352864,
        "public_score": 0.38308
    },
    {
        "version": "sub_v010_catboost_alpha_pack_dropmissing",
        "dataset": "Drop missing train",
        "rows": len(train),
        "cv_rmse": np.mean(rmse_scores),
        "cv_mae": np.mean(mae_scores),
        "cv_r2": np.mean(r2_scores),
        "public_score": None
    }
])

comparison["rmse_vs_previous"] = comparison["cv_rmse"] - comparison.loc[0, "cv_rmse"]
comparison["mae_vs_previous"] = comparison["cv_mae"] - comparison.loc[0, "cv_mae"]
comparison["r2_vs_previous"] = comparison["cv_r2"] - comparison.loc[0, "cv_r2"]

os.makedirs("../reports", exist_ok=True)

comparison.to_csv(
    "../reports/catboost_alpha_pack_dropmissing_comparison.csv",
    index=False
)

print("\nComparison with previous best:")
display(comparison)

Train path: ../MLOpsedian/data/processed/train_dropmissing.csv
Test path: ../MLOpsedian/data/processed/test_dropmissing.csv
Train shape: (15518, 69)
Test shape: (5300, 68)
Train missing: 0
Test missing: 0
Duplicate train IDs: 0
Duplicate test IDs: 0
Train-only columns: {'flood_risk_score'}
Test-only columns: set()
Target valid: True

After feature engineering:
Train shape: (15518, 73)
Test shape: (5300, 72)
Train missing: 0
Test missing: 0

Feature check:
Number of alpha pack features: 35
Missing train features: []
Missing test features: []

Model data:
X shape: (15518, 35)
y shape: (15518,)
X_test shape: (5300, 35)
Missing in X: 0
Missing in X_test: 0
Feature columns match: True

Categorical features:
Number of categorical features: 10
['district', 'generation_date', 'reason_not_good_to_live', 'road_quality', 'landcover', 'place_name', 'water_supply', 'water_presence_flag', 'flood_occurrence_current_event', 'soil_type']

Target bin distribution:
flood_risk_score
0    1899
1    3455
2    5993
3    2655
4    1516
Name: count, dtype: int64

======================================================================
Fold 1
0:	learn: 0.2364969	test: 0.2360924	best: 0.2360924 (0)	total: 90.9ms	remaining: 3m 1s
200:	learn: 0.2275852	test: 0.2317461	best: 0.2317230 (182)	total: 2.25s	remaining: 20.1s
400:	learn: 0.2230408	test: 0.2317122	best: 0.2316819 (351)	total: 5.08s	remaining: 20.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2316819405
bestIteration = 351

Shrink model to first 352 iterations.
Fold RMSE: 0.23168194068370526
Fold MAE : 0.17632492961934465
Fold R²  : 0.038713533847676174

======================================================================
Fold 2
0:	learn: 0.2367391	test: 0.2350707	best: 0.2350707 (0)	total: 9.72ms	remaining: 19.4s
200:	learn: 0.2275708	test: 0.2305723	best: 0.2305723 (200)	total: 3.28s	remaining: 29.4s
400:	learn: 0.2228171	test: 0.2302532	best: 0.2302520 (396)	total: 6.81s	remaining: 27.2s
600:	learn: 0.2174353	test: 0.2303459	best: 0.2302005 (420)	total: 10.1s	remaining: 23.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2302004942
bestIteration = 420

Shrink model to first 421 iterations.
Fold RMSE: 0.23020049457971475
Fold MAE : 0.1750286484506056
Fold R²  : 0.042441308901750685

======================================================================
Fold 3
0:	learn: 0.2367448	test: 0.2350777	best: 0.2350777 (0)	total: 10.3ms	remaining: 20.7s
200:	learn: 0.2276827	test: 0.2307507	best: 0.2306751 (155)	total: 3.71s	remaining: 33.2s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2306750845
bestIteration = 155

Shrink model to first 156 iterations.
Fold RMSE: 0.23067508452663343
Fold MAE : 0.17605041651151615
Fold R²  : 0.03861401008860399

======================================================================
Fold 4
0:	learn: 0.2360616	test: 0.2380016	best: 0.2380016 (0)	total: 9.81ms	remaining: 19.6s
200:	learn: 0.2268862	test: 0.2337250	best: 0.2337236 (198)	total: 3.22s	remaining: 28.8s
400:	learn: 0.2222473	test: 0.2336592	best: 0.2335316 (355)	total: 6.43s	remaining: 25.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.233531603
bestIteration = 355

Shrink model to first 356 iterations.
Fold RMSE: 0.23353160319073427
Fold MAE : 0.17716696509459645
Fold R²  : 0.038388819490463244

======================================================================
Fold 5
0:	learn: 0.2360503	test: 0.2379286	best: 0.2379286 (0)	total: 12ms	remaining: 23.9s
200:	learn: 0.2271257	test: 0.2332481	best: 0.2332481 (200)	total: 3.18s	remaining: 28.5s
400:	learn: 0.2227563	test: 0.2330566	best: 0.2330174 (350)	total: 6.4s	remaining: 25.5s
600:	learn: 0.2176147	test: 0.2330573	best: 0.2329347 (480)	total: 9.69s	remaining: 22.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2329346713
bestIteration = 480

Shrink model to first 481 iterations.
Fold RMSE: 0.2329346711939401
Fold MAE : 0.17845757243953456
Fold R²  : 0.04300666896576666

======================================================================
CatBoost Alpha Pack Drop-Missing CV Results
Average RMSE: 0.23180475883494558
Average MAE : 0.17660570642311946
Average R²  : 0.04023286825885215

Prediction distribution:
Prediction min: 0.3678271653498627
Prediction max: 0.6323633148781503
Prediction mean: 0.47911283671415483
Prediction std: 0.044751843087494254

Submission shape: (5300, 2)
  record_id  flood_risk_score
0   F104559          0.470452
1   F100765          0.442997
2   F107573          0.467572
3   F110345          0.562660
4   F118850          0.517468

Missing values:
record_id           0
flood_risk_score    0
dtype: int64

Prediction range:
Min: 0.3678271653498627
Max: 0.6323633148781503

Submission is valid.

Saved: ../submissions/sub_v010_catboost_alpha_pack_dropmissing.csv

Comparison with previous best:

,version,dataset,rows,cv_rmse,cv_mae,cv_r2,public_score,rmse_vs_previous,mae_vs_previous,r2_vs_previous
0,sub_v008_catboost_alpha_pack,Full cleaned train,19700,0.231648,0.176737,0.034630,0.38308,0.000000,0.000000,0.000000
1,sub_v010_catboost_alpha_pack_dropmissing,Drop missing train,15518,0.231805,0.176606,0.040233,NaN,0.000157,-0.000132,0.005603

In [4]:
# ============================================================
# CatBoost Alpha Pack on Drop-Missing + Invalid-Removed Dataset
# One-cell version
# ============================================================

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from catboost import CatBoostRegressor

# ============================================================
# 1. Load strict-clean datasets
# ============================================================

train_path = "../MLOpsedian/data/processed/train_dropmissing_invalid.csv"
test_path = "../MLOpsedian/data/processed/test_dropmissing_invalid.csv"



train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

id_col = "record_id"
target = "flood_risk_score"

print("Train path:", train_path)
print("Test path:", test_path)
print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Train missing:", train.isnull().sum().sum())
print("Test missing:", test.isnull().sum().sum())
print("Duplicate train IDs:", train[id_col].duplicated().sum())
print("Duplicate test IDs:", test[id_col].duplicated().sum())
print("Train-only columns:", set(train.columns) - set(test.columns))
print("Test-only columns:", set(test.columns) - set(train.columns))
print("Target valid:", train[target].between(0, 1).all())

# ============================================================
# 2. Add Alpha Pack engineered features
# ============================================================

def add_alpha_pack_features(df):
    df = df.copy()
    eps = 1e-5
    
    if "distance_to_river_m_clipped" in df.columns:
        distance = df["distance_to_river_m_clipped"]
    else:
        distance = df["distance_to_river_m"].clip(lower=0)
    
    if "rainfall_7d_mm_clipped" in df.columns:
        rainfall_7d = df["rainfall_7d_mm_clipped"]
    else:
        rainfall_7d = df["rainfall_7d_mm"].clip(lower=0)
    
    inundation = df["inundation_area_sqm"].clip(lower=0)
    
    df["GOLDEN_distance_rainfall_ratio"] = (
        np.log1p(distance) - np.log1p(rainfall_7d + eps)
    )
    
    df["distance_to_river_DIV_inundation_area"] = (
        distance / (inundation + eps)
    )
    
    df["distance_to_river_DIV_rainfall_7d"] = (
        distance / (rainfall_7d + eps)
    )
    
    df["rainfall_7d_MULT_inundation_area"] = (
        rainfall_7d * inundation
    )
    
    new_cols = [
        "GOLDEN_distance_rainfall_ratio",
        "distance_to_river_DIV_inundation_area",
        "distance_to_river_DIV_rainfall_7d",
        "rainfall_7d_MULT_inundation_area"
    ]
    
    for col in new_cols:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
        df[col] = df[col].fillna(df[col].median())
    
    return df

train_fe = add_alpha_pack_features(train)
test_fe = add_alpha_pack_features(test)

print("\nAfter feature engineering:")
print("Train shape:", train_fe.shape)
print("Test shape:", test_fe.shape)
print("Train missing:", train_fe.isnull().sum().sum())
print("Test missing:", test_fe.isnull().sum().sum())

# ============================================================
# 3. Define Alpha Pack features
# ============================================================

alpha_pack_features = [
    "district",
    "distance_to_river_DIV_inundation_area",
    "distance_to_river_DIV_rainfall_7d",
    "GOLDEN_distance_rainfall_ratio",
    "generation_date",
    "reason_not_good_to_live",
    "inundation_area_sqm",
    "infrastructure_score",
    "extreme_weather_index",
    "terrain_roughness_index",
    "road_quality",
    "monthly_rainfall_mm_log1p",
    "landcover",
    "rainfall_7d_MULT_inundation_area",
    "place_name",
    "rainfall_7d_mm",
    "seasonal_index",
    "ndwi_qmap",
    "latitude",
    "longitude",
    "distance_to_river_m",
    "ndwi",
    "water_supply",
    "nearest_evac_km_log1p",
    "elevation_m_yeojohnson",
    "monthly_rainfall_mm",
    "socioeconomic_status_index",
    "population_density_per_km2_log1p",
    "water_presence_flag",
    "nearest_hospital_km_log1p",
    "ndvi_qmap",
    "flood_occurrence_current_event",
    "rainfall_7d_mm_log1p",
    "soil_type",
    "population_density_per_km2"
]

missing_train_features = [col for col in alpha_pack_features if col not in train_fe.columns]
missing_test_features = [col for col in alpha_pack_features if col not in test_fe.columns]

print("\nFeature check:")
print("Number of alpha pack features:", len(alpha_pack_features))
print("Missing train features:", missing_train_features)
print("Missing test features:", missing_test_features)

if len(missing_train_features) > 0 or len(missing_test_features) > 0:
    raise ValueError("Some alpha pack features are missing. Stop and check columns.")

# ============================================================
# 4. Prepare X, y, X_test
# ============================================================

X = train_fe[alpha_pack_features].copy()
y = train_fe[target].copy()

X_test = test_fe[alpha_pack_features].copy()
test_ids = test_fe[id_col].copy()

print("\nModel data:")
print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)
print("Missing in X:", X.isnull().sum().sum())
print("Missing in X_test:", X_test.isnull().sum().sum())
print("Feature columns match:", list(X.columns) == list(X_test.columns))

# ============================================================
# 5. Identify categorical features
# ============================================================

cat_features = [
    col for col in X.columns
    if X[col].dtype == "object" or str(X[col].dtype) == "str"
]

print("\nCategorical features:")
print("Number of categorical features:", len(cat_features))
print(cat_features)

# ============================================================
# 6. Target bins for balance-aware StratifiedKFold
# ============================================================

target_bins = pd.cut(
    y,
    bins=[-0.001, 0.2, 0.4, 0.6, 0.8, 1.001],
    labels=[0, 1, 2, 3, 4]
)

print("\nTarget bin distribution:")
print(target_bins.value_counts().sort_index())

# ============================================================
# 7. Submission validation function
# ============================================================

def validate_submission(submission):
    print("\nSubmission shape:", submission.shape)
    print(submission.head())
    
    print("\nMissing values:")
    print(submission.isnull().sum())
    
    print("\nPrediction range:")
    print("Min:", submission["flood_risk_score"].min())
    print("Max:", submission["flood_risk_score"].max())
    
    assert submission.shape[0] == len(test_ids)
    assert list(submission.columns) == ["record_id", "flood_risk_score"]
    assert submission["flood_risk_score"].isnull().sum() == 0
    assert submission["flood_risk_score"].between(0, 1).all()
    
    print("\nSubmission is valid.")

# ============================================================
# 8. Train CatBoost Alpha Pack on strict-clean data
# ============================================================

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

rmse_scores = []
mae_scores = []
r2_scores = []

test_preds = np.zeros(len(X_test))

for fold, (train_idx, valid_idx) in enumerate(skf.split(X, target_bins), 1):
    print("\n" + "=" * 70)
    print(f"Fold {fold}")
    
    X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
    y_train, y_valid = y.iloc[train_idx], y.iloc[valid_idx]
    
    model = CatBoostRegressor(
        iterations=2000,
        learning_rate=0.03,
        depth=6,
        loss_function="RMSE",
        eval_metric="RMSE",
        random_seed=42 + fold,
        verbose=200,
        early_stopping_rounds=200,
        allow_writing_files=False
    )
    
    model.fit(
        X_train,
        y_train,
        cat_features=cat_features,
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )
    
    valid_preds = model.predict(X_valid)
    valid_preds = np.clip(valid_preds, 0, 1)
    
    rmse = np.sqrt(mean_squared_error(y_valid, valid_preds))
    mae = mean_absolute_error(y_valid, valid_preds)
    r2 = r2_score(y_valid, valid_preds)
    
    rmse_scores.append(rmse)
    mae_scores.append(mae)
    r2_scores.append(r2)
    
    print("Fold RMSE:", rmse)
    print("Fold MAE :", mae)
    print("Fold R²  :", r2)
    
    fold_test_preds = model.predict(X_test)
    test_preds += fold_test_preds / skf.n_splits

print("\n" + "=" * 70)
print("CatBoost Alpha Pack Drop-Missing + Invalid CV Results")
print("Average RMSE:", np.mean(rmse_scores))
print("Average MAE :", np.mean(mae_scores))
print("Average R²  :", np.mean(r2_scores))

# ============================================================
# 9. Create submission
# ============================================================

strict_preds = np.clip(test_preds, 0, 1)

print("\nPrediction distribution:")
print("Prediction min:", strict_preds.min())
print("Prediction max:", strict_preds.max())
print("Prediction mean:", strict_preds.mean())
print("Prediction std:", strict_preds.std())

sub_strict = pd.DataFrame({
    "record_id": test_ids,
    "flood_risk_score": strict_preds
})

validate_submission(sub_strict)

os.makedirs("../submissions", exist_ok=True)

sub_strict.to_csv(
    "../submissions/sub_v011_catboost_alpha_pack_dropmissing_invalid.csv",
    index=False
)

print("\nSaved: ../submissions/sub_v011_catboost_alpha_pack_dropmissing_invalid.csv")

# ============================================================
# 10. Compare with previous best versions
# ============================================================

comparison = pd.DataFrame([
    {
        "version": "sub_v008_catboost_alpha_pack",
        "dataset": "Full cleaned train",
        "rows": 19700,
        "cv_rmse": 0.23164778640435246,
        "cv_mae": 0.17673736118136243,
        "cv_r2": 0.03463008143352864,
        "public_score": 0.38308
    },
    {
        "version": "sub_v010_catboost_alpha_pack_dropmissing",
        "dataset": "Drop missing train",
        "rows": 15518,
        "cv_rmse": 0.23180475883494558,
        "cv_mae": 0.17660570642311946,
        "cv_r2": 0.04023286825885215,
        "public_score": 0.38176
    },
    {
        "version": "sub_v011_catboost_alpha_pack_dropmissing_invalid",
        "dataset": "Drop missing + invalid train",
        "rows": len(train),
        "cv_rmse": np.mean(rmse_scores),
        "cv_mae": np.mean(mae_scores),
        "cv_r2": np.mean(r2_scores),
        "public_score": None
    }
])

comparison["rmse_vs_best_public"] = comparison["cv_rmse"] - comparison.loc[1, "cv_rmse"]
comparison["mae_vs_best_public"] = comparison["cv_mae"] - comparison.loc[1, "cv_mae"]
comparison["r2_vs_best_public"] = comparison["cv_r2"] - comparison.loc[1, "cv_r2"]

os.makedirs("../reports", exist_ok=True)

comparison.to_csv(
    "../reports/catboost_alpha_pack_strict_clean_comparison.csv",
    index=False
)

print("\nComparison with previous versions:")
display(comparison)

Train path: ../MLOpsedian/data/processed/train_dropmissing_invalid.csv
Test path: ../MLOpsedian/data/processed/test_dropmissing_invalid.csv
Train shape: (14921, 69)
Test shape: (5300, 68)
Train missing: 0
Test missing: 0
Duplicate train IDs: 0
Duplicate test IDs: 0
Train-only columns: {'flood_risk_score'}
Test-only columns: set()
Target valid: True

After feature engineering:
Train shape: (14921, 73)
Test shape: (5300, 72)
Train missing: 0
Test missing: 0

Feature check:
Number of alpha pack features: 35
Missing train features: []
Missing test features: []

Model data:
X shape: (14921, 35)
y shape: (14921,)
X_test shape: (5300, 35)
Missing in X: 0
Missing in X_test: 0
Feature columns match: True

Categorical features:
Number of categorical features: 10
['district', 'generation_date', 'reason_not_good_to_live', 'road_quality', 'landcover', 'place_name', 'water_supply', 'water_presence_flag', 'flood_occurrence_current_event', 'soil_type']

Target bin distribution:
flood_risk_score
0    1816
1    3338
2    5757
3    2561
4    1449
Name: count, dtype: int64

======================================================================
Fold 1
0:	learn: 0.2362081	test: 0.2360911	best: 0.2360911 (0)	total: 38.6ms	remaining: 1m 17s
200:	learn: 0.2270749	test: 0.2327292	best: 0.2326824 (153)	total: 2.69s	remaining: 24s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.23268237
bestIteration = 153

Shrink model to first 154 iterations.
Fold RMSE: 0.23268237010090173
Fold MAE : 0.17703623434584326
Fold R²  : 0.03009735944290992

======================================================================
Fold 2
0:	learn: 0.2361540	test: 0.2360631	best: 0.2360631 (0)	total: 8.7ms	remaining: 17.4s
200:	learn: 0.2271858	test: 0.2321951	best: 0.2321915 (199)	total: 2.63s	remaining: 23.6s
400:	learn: 0.2227089	test: 0.2321856	best: 0.2320934 (281)	total: 5.43s	remaining: 21.7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.232093395
bestIteration = 281

Shrink model to first 282 iterations.
Fold RMSE: 0.2320933949186535
Fold MAE : 0.17742519383105454
Fold R²  : 0.03470966758742389

======================================================================
Fold 3
0:	learn: 0.2355833	test: 0.2387004	best: 0.2387004 (0)	total: 8.46ms	remaining: 16.9s
200:	learn: 0.2268266	test: 0.2340718	best: 0.2340718 (200)	total: 2.69s	remaining: 24.1s
400:	learn: 0.2221480	test: 0.2340720	best: 0.2339164 (325)	total: 5.81s	remaining: 23.2s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2339164278
bestIteration = 325

Shrink model to first 326 iterations.
Fold RMSE: 0.23391642825546233
Fold MAE : 0.17827784841319494
Fold R²  : 0.040803839741599846

======================================================================
Fold 4
0:	learn: 0.2366348	test: 0.2344555	best: 0.2344555 (0)	total: 10.9ms	remaining: 21.7s
200:	learn: 0.2273734	test: 0.2294548	best: 0.2294513 (198)	total: 2.79s	remaining: 24.9s
400:	learn: 0.2224128	test: 0.2292639	best: 0.2292137 (319)	total: 5.58s	remaining: 22.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2292137236
bestIteration = 319

Shrink model to first 320 iterations.
Fold RMSE: 0.2292137236089774
Fold MAE : 0.17521542688825634
Fold R²  : 0.0456218546961078

======================================================================
Fold 5
0:	learn: 0.2362993	test: 0.2356416	best: 0.2356416 (0)	total: 10.2ms	remaining: 20.4s
200:	learn: 0.2274691	test: 0.2303182	best: 0.2303171 (199)	total: 2.81s	remaining: 25.1s
400:	learn: 0.2227498	test: 0.2304101	best: 0.2302358 (225)	total: 5.73s	remaining: 22.9s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2302358001
bestIteration = 225

Shrink model to first 226 iterations.
Fold RMSE: 0.23023580018963624
Fold MAE : 0.17561149479384694
Fold R²  : 0.0468884011918671

======================================================================
CatBoost Alpha Pack Drop-Missing + Invalid CV Results
Average RMSE: 0.23162834341472624
Average MAE : 0.1767132396544392
Average R²  : 0.03962422453198171

Prediction distribution:
Prediction min: 0.3766668028864936
Prediction max: 0.6194637458159771
Prediction mean: 0.4788144556711817
Prediction std: 0.04174568759804983

Submission shape: (5300, 2)
  record_id  flood_risk_score
0   F104559          0.476864
1   F100765          0.449154
2   F107573          0.478288
3   F110345          0.542641
4   F118850          0.508234

Missing values:
record_id           0
flood_risk_score    0
dtype: int64

Prediction range:
Min: 0.3766668028864936
Max: 0.6194637458159771

Submission is valid.

Saved: ../submissions/sub_v011_catboost_alpha_pack_dropmissing_invalid.csv

Comparison with previous versions:

,version,dataset,rows,cv_rmse,cv_mae,cv_r2,public_score,rmse_vs_best_public,mae_vs_best_public,r2_vs_best_public
0,sub_v008_catboost_alpha_pack,Full cleaned train,19700,0.231648,0.176737,0.034630,0.38308,-0.000157,0.000132,-0.005603
1,sub_v010_catboost_alpha_pack_dropmissing,Drop missing train,15518,0.231805,0.176606,0.040233,0.38176,0.000000,0.000000,0.000000
2,sub_v011_catboost_alpha_pack_dropmissing_invalid,Drop missing + invalid train,14921,0.231628,0.176713,0.039624,NaN,-0.000176,0.000108,-0.000609

In [5]:
# ============================================================
# V012: CatBoost Full + Alpha Features on Drop-Missing Dataset
# ============================================================

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from catboost import CatBoostRegressor

# ============================================================
# 1. Load drop-missing datasets
# ============================================================

train_path = "../data/processed/train_dropmissing.csv"
test_path = "../data/processed/test_dropmissing.csv"

# Backup path if your project folder is one level different
if not os.path.exists(train_path):
    train_path = "../MLOpsedian/data/processed/train_dropmissing.csv"
    test_path = "../MLOpsedian/data/processed/test_dropmissing.csv"

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

id_col = "record_id"
target = "flood_risk_score"

print("Train path:", train_path)
print("Test path:", test_path)
print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Train missing:", train.isnull().sum().sum())
print("Test missing:", test.isnull().sum().sum())
print("Duplicate train IDs:", train[id_col].duplicated().sum())
print("Duplicate test IDs:", test[id_col].duplicated().sum())
print("Train-only columns:", set(train.columns) - set(test.columns))
print("Test-only columns:", set(test.columns) - set(train.columns))
print("Target valid:", train[target].between(0, 1).all())

# ============================================================
# 2. Add Alpha Pack engineered features
# ============================================================

def add_alpha_pack_features(df):
    df = df.copy()
    eps = 1e-5
    
    if "distance_to_river_m_clipped" in df.columns:
        distance = df["distance_to_river_m_clipped"]
    else:
        distance = df["distance_to_river_m"].clip(lower=0)
    
    if "rainfall_7d_mm_clipped" in df.columns:
        rainfall_7d = df["rainfall_7d_mm_clipped"]
    else:
        rainfall_7d = df["rainfall_7d_mm"].clip(lower=0)
    
    inundation = df["inundation_area_sqm"].clip(lower=0)
    
    df["GOLDEN_distance_rainfall_ratio"] = (
        np.log1p(distance) - np.log1p(rainfall_7d + eps)
    )
    
    df["distance_to_river_DIV_inundation_area"] = (
        distance / (inundation + eps)
    )
    
    df["distance_to_river_DIV_rainfall_7d"] = (
        distance / (rainfall_7d + eps)
    )
    
    df["rainfall_7d_MULT_inundation_area"] = (
        rainfall_7d * inundation
    )
    
    new_cols = [
        "GOLDEN_distance_rainfall_ratio",
        "distance_to_river_DIV_inundation_area",
        "distance_to_river_DIV_rainfall_7d",
        "rainfall_7d_MULT_inundation_area"
    ]
    
    for col in new_cols:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
        df[col] = df[col].fillna(df[col].median())
    
    return df

train_fe = add_alpha_pack_features(train)
test_fe = add_alpha_pack_features(test)

print("\nAfter feature engineering:")
print("Train shape:", train_fe.shape)
print("Test shape:", test_fe.shape)
print("Train missing:", train_fe.isnull().sum().sum())
print("Test missing:", test_fe.isnull().sum().sum())

# ============================================================
# 3. Use Full Features + Alpha Features
# ============================================================

base_drop_cols = [
    id_col,
    target,
    "generation_date_missing"
]

# Drop any feature that is constant in train because it gives no learning signal
constant_train_cols = [
    col for col in train_fe.columns
    if col not in base_drop_cols and train_fe[col].nunique(dropna=False) <= 1
]

drop_cols = base_drop_cols + constant_train_cols

feature_cols = [
    col for col in train_fe.columns
    if col not in drop_cols
]

print("\nDropped columns:")
print(drop_cols)

print("\nNumber of features used:", len(feature_cols))
print("Constant columns dropped:", constant_train_cols)

# Check feature alignment
missing_test_features = [col for col in feature_cols if col not in test_fe.columns]
print("Missing test features:", missing_test_features)

if len(missing_test_features) > 0:
    raise ValueError("Some train features are missing in test. Stop and check.")

# ============================================================
# 4. Prepare X, y, X_test
# ============================================================

X = train_fe[feature_cols].copy()
y = train_fe[target].copy()

X_test = test_fe[feature_cols].copy()
test_ids = test_fe[id_col].copy()

print("\nModel data:")
print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)
print("Missing in X:", X.isnull().sum().sum())
print("Missing in X_test:", X_test.isnull().sum().sum())
print("Feature columns match:", list(X.columns) == list(X_test.columns))

# ============================================================
# 5. Identify categorical features
# ============================================================

cat_features = [
    col for col in X.columns
    if X[col].dtype == "object" or str(X[col].dtype) == "str"
]

print("\nCategorical features:")
print("Number of categorical features:", len(cat_features))
print(cat_features)

# ============================================================
# 6. Target bins for balance-aware StratifiedKFold
# ============================================================

target_bins = pd.cut(
    y,
    bins=[-0.001, 0.2, 0.4, 0.6, 0.8, 1.001],
    labels=[0, 1, 2, 3, 4]
)

print("\nTarget bin distribution:")
print(target_bins.value_counts().sort_index())

# ============================================================
# 7. Submission validation function
# ============================================================

def validate_submission(submission):
    print("\nSubmission shape:", submission.shape)
    print(submission.head())
    
    print("\nMissing values:")
    print(submission.isnull().sum())
    
    print("\nPrediction range:")
    print("Min:", submission["flood_risk_score"].min())
    print("Max:", submission["flood_risk_score"].max())
    
    assert submission.shape[0] == len(test_ids)
    assert list(submission.columns) == ["record_id", "flood_risk_score"]
    assert submission["flood_risk_score"].isnull().sum() == 0
    assert submission["flood_risk_score"].between(0, 1).all()
    
    print("\nSubmission is valid.")

# ============================================================
# 8. Train CatBoost Full + Alpha on drop-missing data
# ============================================================

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

rmse_scores = []
mae_scores = []
r2_scores = []

test_preds = np.zeros(len(X_test))

for fold, (train_idx, valid_idx) in enumerate(skf.split(X, target_bins), 1):
    print("\n" + "=" * 70)
    print(f"Fold {fold}")
    
    X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
    y_train, y_valid = y.iloc[train_idx], y.iloc[valid_idx]
    
    model = CatBoostRegressor(
        iterations=2000,
        learning_rate=0.03,
        depth=6,
        loss_function="RMSE",
        eval_metric="RMSE",
        random_seed=42 + fold,
        verbose=200,
        early_stopping_rounds=200,
        allow_writing_files=False
    )
    
    model.fit(
        X_train,
        y_train,
        cat_features=cat_features,
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )
    
    valid_preds = model.predict(X_valid)
    valid_preds = np.clip(valid_preds, 0, 1)
    
    rmse = np.sqrt(mean_squared_error(y_valid, valid_preds))
    mae = mean_absolute_error(y_valid, valid_preds)
    r2 = r2_score(y_valid, valid_preds)
    
    rmse_scores.append(rmse)
    mae_scores.append(mae)
    r2_scores.append(r2)
    
    print("Fold RMSE:", rmse)
    print("Fold MAE :", mae)
    print("Fold R²  :", r2)
    
    fold_test_preds = model.predict(X_test)
    test_preds += fold_test_preds / skf.n_splits

print("\n" + "=" * 70)
print("CatBoost Full + Alpha Drop-Missing CV Results")
print("Average RMSE:", np.mean(rmse_scores))
print("Average MAE :", np.mean(mae_scores))
print("Average R²  :", np.mean(r2_scores))

# ============================================================
# 9. Create submission
# ============================================================

full_alpha_preds = np.clip(test_preds, 0, 1)

print("\nPrediction distribution:")
print("Prediction min:", full_alpha_preds.min())
print("Prediction max:", full_alpha_preds.max())
print("Prediction mean:", full_alpha_preds.mean())
print("Prediction std:", full_alpha_preds.std())

sub_full_alpha = pd.DataFrame({
    "record_id": test_ids,
    "flood_risk_score": full_alpha_preds
})

validate_submission(sub_full_alpha)

os.makedirs("../submissions", exist_ok=True)

sub_full_alpha.to_csv(
    "../submissions/sub_v012_catboost_full_plus_alpha_dropmissing.csv",
    index=False
)

print("\nSaved: ../submissions/sub_v012_catboost_full_plus_alpha_dropmissing.csv")

# ============================================================
# 10. Compare with previous versions
# ============================================================

comparison = pd.DataFrame([
    {
        "version": "sub_v008_catboost_alpha_pack",
        "dataset": "Full cleaned train",
        "features": "35 Alpha Pack",
        "rows": 19700,
        "cv_rmse": 0.23164778640435246,
        "cv_mae": 0.17673736118136243,
        "cv_r2": 0.03463008143352864,
        "prediction_std": 0.042242,
        "public_score": 0.38308
    },
    {
        "version": "sub_v010_catboost_alpha_pack_dropmissing",
        "dataset": "Drop missing train",
        "features": "35 Alpha Pack",
        "rows": 15518,
        "cv_rmse": 0.23180475883494558,
        "cv_mae": 0.17660570642311946,
        "cv_r2": 0.04023286825885215,
        "prediction_std": 0.044751843087494254,
        "public_score": 0.38176
    },
    {
        "version": "sub_v011_catboost_alpha_pack_dropmissing_invalid",
        "dataset": "Drop missing + invalid train",
        "features": "35 Alpha Pack",
        "rows": 14921,
        "cv_rmse": 0.23162834341472624,
        "cv_mae": 0.1767132396544392,
        "cv_r2": 0.03962422453198171,
        "prediction_std": 0.04174568759804983,
        "public_score": 0.38309
    },
    {
        "version": "sub_v012_catboost_full_plus_alpha_dropmissing",
        "dataset": "Drop missing train",
        "features": f"Full + Alpha ({len(feature_cols)} features)",
        "rows": len(train),
        "cv_rmse": np.mean(rmse_scores),
        "cv_mae": np.mean(mae_scores),
        "cv_r2": np.mean(r2_scores),
        "prediction_std": full_alpha_preds.std(),
        "public_score": None
    }
])

comparison["rmse_vs_best_public"] = comparison["cv_rmse"] - comparison.loc[1, "cv_rmse"]
comparison["mae_vs_best_public"] = comparison["cv_mae"] - comparison.loc[1, "cv_mae"]
comparison["r2_vs_best_public"] = comparison["cv_r2"] - comparison.loc[1, "cv_r2"]
comparison["pred_std_vs_best_public"] = comparison["prediction_std"] - comparison.loc[1, "prediction_std"]

os.makedirs("../reports", exist_ok=True)

comparison.to_csv(
    "../reports/catboost_full_plus_alpha_dropmissing_comparison.csv",
    index=False
)

print("\nComparison with previous versions:")
display(comparison)

Train path: ../MLOpsedian/data/processed/train_dropmissing.csv
Test path: ../MLOpsedian/data/processed/test_dropmissing.csv
Train shape: (15518, 69)
Test shape: (5300, 68)
Train missing: 0
Test missing: 0
Duplicate train IDs: 0
Duplicate test IDs: 0
Train-only columns: {'flood_risk_score'}
Test-only columns: set()
Target valid: True

After feature engineering:
Train shape: (15518, 73)
Test shape: (5300, 72)
Train missing: 0
Test missing: 0

Dropped columns:
['record_id', 'flood_risk_score', 'generation_date_missing']

Number of features used: 70
Constant columns dropped: []
Missing test features: []

Model data:
X shape: (15518, 70)
y shape: (15518,)
X_test shape: (5300, 70)
Missing in X: 0
Missing in X_test: 0
Feature columns match: True

Categorical features:
Number of categorical features: 14
['district', 'place_name', 'landcover', 'soil_type', 'water_supply', 'electricity', 'road_quality', 'urban_rural', 'water_presence_flag', 'flood_occurrence_current_event', 'is_good_to_live', 'reason_not_good_to_live', 'is_synthetic', 'generation_date']

Target bin distribution:
flood_risk_score
0    1899
1    3455
2    5993
3    2655
4    1516
Name: count, dtype: int64

======================================================================
Fold 1
0:	learn: 0.2364946	test: 0.2361105	best: 0.2361105 (0)	total: 31.6ms	remaining: 1m 3s
200:	learn: 0.2272403	test: 0.2319104	best: 0.2318164 (152)	total: 3.2s	remaining: 28.7s
400:	learn: 0.2220926	test: 0.2318717	best: 0.2318087 (355)	total: 6.61s	remaining: 26.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.231808733
bestIteration = 355

Shrink model to first 356 iterations.
Fold RMSE: 0.23180873319150502
Fold MAE : 0.1764402551211815
Fold R²  : 0.03766108001302049

======================================================================
Fold 2
0:	learn: 0.2367897	test: 0.2351077	best: 0.2351077 (0)	total: 10.9ms	remaining: 21.8s
200:	learn: 0.2273737	test: 0.2305878	best: 0.2305789 (199)	total: 3.27s	remaining: 29.2s
400:	learn: 0.2227415	test: 0.2304384	best: 0.2304280 (397)	total: 6.52s	remaining: 26s
600:	learn: 0.2176457	test: 0.2304261	best: 0.2303728 (576)	total: 9.87s	remaining: 23s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2303728329
bestIteration = 576

Shrink model to first 577 iterations.
Fold RMSE: 0.23037283324993438
Fold MAE : 0.17505879411468772
Fold R²  : 0.04100702732729533

======================================================================
Fold 3
0:	learn: 0.2367787	test: 0.2350850	best: 0.2350850 (0)	total: 6.79ms	remaining: 13.6s
200:	learn: 0.2274695	test: 0.2305819	best: 0.2305266 (161)	total: 3.36s	remaining: 30.1s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2305266065
bestIteration = 161

Shrink model to first 162 iterations.
Fold RMSE: 0.23052660651649387
Fold MAE : 0.1759669091613936
Fold R²  : 0.03985123723872752

======================================================================
Fold 4
0:	learn: 0.2360523	test: 0.2380205	best: 0.2380205 (0)	total: 10.1ms	remaining: 20.2s
200:	learn: 0.2265662	test: 0.2338987	best: 0.2338905 (199)	total: 3.19s	remaining: 28.5s
400:	learn: 0.2216566	test: 0.2338007	best: 0.2337579 (279)	total: 6.95s	remaining: 27.7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2337578596
bestIteration = 279

Shrink model to first 280 iterations.
Fold RMSE: 0.23375785978038208
Fold MAE : 0.17760711407749713
Fold R²  : 0.036524607025621325

======================================================================
Fold 5
0:	learn: 0.2360442	test: 0.2379096	best: 0.2379096 (0)	total: 11.6ms	remaining: 23.2s
200:	learn: 0.2269433	test: 0.2334494	best: 0.2334414 (163)	total: 3.36s	remaining: 30.1s
400:	learn: 0.2222621	test: 0.2333363	best: 0.2332761 (347)	total: 6.71s	remaining: 26.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2332761354
bestIteration = 347

Shrink model to first 348 iterations.
Fold RMSE: 0.23327613529774432
Fold MAE : 0.17851888899669127
Fold R²  : 0.0401988569328835

======================================================================
CatBoost Full + Alpha Drop-Missing CV Results
Average RMSE: 0.2319484336072119
Average MAE : 0.17671839229429026
Average R²  : 0.03904856170750963

Prediction distribution:
Prediction min: 0.3682653860506179
Prediction max: 0.6244670524423802
Prediction mean: 0.47946005687460574
Prediction std: 0.04360086243404623

Submission shape: (5300, 2)
  record_id  flood_risk_score
0   F104559          0.472363
1   F100765          0.452168
2   F107573          0.470430
3   F110345          0.557211
4   F118850          0.501088

Missing values:
record_id           0
flood_risk_score    0
dtype: int64

Prediction range:
Min: 0.3682653860506179
Max: 0.6244670524423802

Submission is valid.

Saved: ../submissions/sub_v012_catboost_full_plus_alpha_dropmissing.csv

Comparison with previous versions:

,version,dataset,features,rows,cv_rmse,cv_mae,cv_r2,prediction_std,public_score,rmse_vs_best_public,mae_vs_best_public,r2_vs_best_public,pred_std_vs_best_public
0,sub_v008_catboost_alpha_pack,Full cleaned train,35 Alpha Pack,19700,0.231648,0.176737,0.034630,0.042242,0.38308,-0.000157,0.000132,-0.005603,-0.002510
1,sub_v010_catboost_alpha_pack_dropmissing,Drop missing train,35 Alpha Pack,15518,0.231805,0.176606,0.040233,0.044752,0.38176,0.000000,0.000000,0.000000,0.000000
2,sub_v011_catboost_alpha_pack_dropmissing_invalid,Drop missing + invalid train,35 Alpha Pack,14921,0.231628,0.176713,0.039624,0.041746,0.38309,-0.000176,0.000108,-0.000609,-0.003006
3,sub_v012_catboost_full_plus_alpha_dropmissing,Drop missing train,Full + Alpha (70 features),15518,0.231948,0.176718,0.039049,0.043601,NaN,0.000144,0.000113,-0.001184,-0.001151

In [6]:
# ============================================================
# V013: Correlation-Guided CatBoost on Drop-Missing Dataset
# Uses 35 Alpha Pack + selected extra correlation-supported features
# ============================================================

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from catboost import CatBoostRegressor

# ============================================================
# 1. Load drop-missing datasets
# ============================================================

train_path = "../data/processed/train_dropmissing.csv"
test_path = "../data/processed/test_dropmissing.csv"

if not os.path.exists(train_path):
    train_path = "../MLOpsedian/data/processed/train_dropmissing.csv"
    test_path = "../MLOpsedian/data/processed/test_dropmissing.csv"

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

id_col = "record_id"
target = "flood_risk_score"

print("Train path:", train_path)
print("Test path:", test_path)
print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Train missing:", train.isnull().sum().sum())
print("Test missing:", test.isnull().sum().sum())
print("Duplicate train IDs:", train[id_col].duplicated().sum())
print("Duplicate test IDs:", test[id_col].duplicated().sum())
print("Train-only columns:", set(train.columns) - set(test.columns))
print("Test-only columns:", set(test.columns) - set(train.columns))
print("Target valid:", train[target].between(0, 1).all())

# ============================================================
# 2. Add Alpha Pack engineered features
# ============================================================

def add_alpha_pack_features(df):
    df = df.copy()
    eps = 1e-5
    
    if "distance_to_river_m_clipped" in df.columns:
        distance = df["distance_to_river_m_clipped"]
    else:
        distance = df["distance_to_river_m"].clip(lower=0)
    
    if "rainfall_7d_mm_clipped" in df.columns:
        rainfall_7d = df["rainfall_7d_mm_clipped"]
    else:
        rainfall_7d = df["rainfall_7d_mm"].clip(lower=0)
    
    inundation = df["inundation_area_sqm"].clip(lower=0)
    
    df["GOLDEN_distance_rainfall_ratio"] = (
        np.log1p(distance) - np.log1p(rainfall_7d + eps)
    )
    
    df["distance_to_river_DIV_inundation_area"] = (
        distance / (inundation + eps)
    )
    
    df["distance_to_river_DIV_rainfall_7d"] = (
        distance / (rainfall_7d + eps)
    )
    
    df["rainfall_7d_MULT_inundation_area"] = (
        rainfall_7d * inundation
    )
    
    new_cols = [
        "GOLDEN_distance_rainfall_ratio",
        "distance_to_river_DIV_inundation_area",
        "distance_to_river_DIV_rainfall_7d",
        "rainfall_7d_MULT_inundation_area"
    ]
    
    for col in new_cols:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
        df[col] = df[col].fillna(df[col].median())
    
    return df

train_fe = add_alpha_pack_features(train)
test_fe = add_alpha_pack_features(test)

print("\nAfter feature engineering:")
print("Train shape:", train_fe.shape)
print("Test shape:", test_fe.shape)
print("Train missing:", train_fe.isnull().sum().sum())
print("Test missing:", test_fe.isnull().sum().sum())

# ============================================================
# 3. V013 correlation-guided feature set
# ============================================================

v013_features = [
    "district",
    "distance_to_river_DIV_inundation_area",
    "distance_to_river_DIV_rainfall_7d",
    "GOLDEN_distance_rainfall_ratio",
    "generation_date",
    "reason_not_good_to_live",
    "inundation_area_sqm",
    "infrastructure_score",
    "extreme_weather_index",
    "terrain_roughness_index",
    "road_quality",
    "monthly_rainfall_mm_log1p",
    "landcover",
    "rainfall_7d_MULT_inundation_area",
    "place_name",
    "rainfall_7d_mm",
    "seasonal_index",
    "ndwi_qmap",
    "latitude",
    "longitude",
    "distance_to_river_m",
    "ndwi",
    "water_supply",
    "nearest_evac_km_log1p",
    "elevation_m_yeojohnson",
    "monthly_rainfall_mm",
    "socioeconomic_status_index",
    "population_density_per_km2_log1p",
    "water_presence_flag",
    "nearest_hospital_km_log1p",
    "ndvi_qmap",
    "flood_occurrence_current_event",
    "rainfall_7d_mm_log1p",
    "soil_type",
    "population_density_per_km2",
    
    # Extra correlation-supported features
    "distance_to_river_m_log1p",
    "distance_to_river_m_clipped",
    "rainfall_7d_mm_clipped",
    "historical_flood_count",
    "monthly_rainfall_mm_clipped",
    "ndwi_clipped",
    "built_up_percent_qmap",
    "built_up_percent",
    "built_up_percent_clipped",
    "drainage_index_yeojohnson",
    "drainage_index",
    "drainage_index_clipped",
    "generation_day",
    "is_good_to_live"
]

# Remove accidental duplicates while preserving order
v013_features = list(dict.fromkeys(v013_features))

missing_train_features = [col for col in v013_features if col not in train_fe.columns]
missing_test_features = [col for col in v013_features if col not in test_fe.columns]

print("\nFeature check:")
print("Number of V013 features:", len(v013_features))
print("Missing train features:", missing_train_features)
print("Missing test features:", missing_test_features)

if len(missing_train_features) > 0 or len(missing_test_features) > 0:
    raise ValueError("Some V013 features are missing. Stop and check columns.")

# ============================================================
# 4. Prepare model data
# ============================================================

X = train_fe[v013_features].copy()
y = train_fe[target].copy()

X_test = test_fe[v013_features].copy()
test_ids = test_fe[id_col].copy()

print("\nModel data:")
print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)
print("Missing in X:", X.isnull().sum().sum())
print("Missing in X_test:", X_test.isnull().sum().sum())
print("Feature columns match:", list(X.columns) == list(X_test.columns))

cat_features = [
    col for col in X.columns
    if X[col].dtype == "object" or str(X[col].dtype) == "str"
]

print("\nCategorical features:")
print("Number of categorical features:", len(cat_features))
print(cat_features)

# ============================================================
# 5. Target-binned StratifiedKFold
# ============================================================

target_bins = pd.cut(
    y,
    bins=[-0.001, 0.2, 0.4, 0.6, 0.8, 1.001],
    labels=[0, 1, 2, 3, 4]
)

print("\nTarget bin distribution:")
print(target_bins.value_counts().sort_index())

# ============================================================
# 6. Submission validation function
# ============================================================

def validate_submission(submission):
    print("\nSubmission shape:", submission.shape)
    print(submission.head())
    
    print("\nMissing values:")
    print(submission.isnull().sum())
    
    print("\nPrediction range:")
    print("Min:", submission["flood_risk_score"].min())
    print("Max:", submission["flood_risk_score"].max())
    
    assert submission.shape[0] == len(test_ids)
    assert list(submission.columns) == ["record_id", "flood_risk_score"]
    assert submission["flood_risk_score"].isnull().sum() == 0
    assert submission["flood_risk_score"].between(0, 1).all()
    
    print("\nSubmission is valid.")

# ============================================================
# 7. Train CatBoost V013
# ============================================================

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

rmse_scores = []
mae_scores = []
r2_scores = []

test_preds = np.zeros(len(X_test))

for fold, (train_idx, valid_idx) in enumerate(skf.split(X, target_bins), 1):
    print("\n" + "=" * 70)
    print(f"Fold {fold}")
    
    X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
    y_train, y_valid = y.iloc[train_idx], y.iloc[valid_idx]
    
    model = CatBoostRegressor(
        iterations=2000,
        learning_rate=0.03,
        depth=6,
        loss_function="RMSE",
        eval_metric="RMSE",
        random_seed=42 + fold,
        verbose=200,
        early_stopping_rounds=200,
        allow_writing_files=False
    )
    
    model.fit(
        X_train,
        y_train,
        cat_features=cat_features,
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )
    
    valid_preds = model.predict(X_valid)
    valid_preds = np.clip(valid_preds, 0, 1)
    
    rmse = np.sqrt(mean_squared_error(y_valid, valid_preds))
    mae = mean_absolute_error(y_valid, valid_preds)
    r2 = r2_score(y_valid, valid_preds)
    
    rmse_scores.append(rmse)
    mae_scores.append(mae)
    r2_scores.append(r2)
    
    print("Fold RMSE:", rmse)
    print("Fold MAE :", mae)
    print("Fold R²  :", r2)
    
    fold_test_preds = model.predict(X_test)
    test_preds += fold_test_preds / skf.n_splits

print("\n" + "=" * 70)
print("V013 Correlation-Guided CatBoost CV Results")
print("Average RMSE:", np.mean(rmse_scores))
print("Average MAE :", np.mean(mae_scores))
print("Average R²  :", np.mean(r2_scores))

# ============================================================
# 8. Create submission
# ============================================================

v013_preds = np.clip(test_preds, 0, 1)

print("\nPrediction distribution:")
print("Prediction min:", v013_preds.min())
print("Prediction max:", v013_preds.max())
print("Prediction mean:", v013_preds.mean())
print("Prediction std:", v013_preds.std())

sub_v013 = pd.DataFrame({
    "record_id": test_ids,
    "flood_risk_score": v013_preds
})

validate_submission(sub_v013)

os.makedirs("../submissions", exist_ok=True)

sub_v013.to_csv(
    "../submissions/sub_v013_catboost_corr_guided_dropmissing.csv",
    index=False
)

print("\nSaved: ../submissions/sub_v013_catboost_corr_guided_dropmissing.csv")

# ============================================================
# 9. Compare with previous versions
# ============================================================

comparison = pd.DataFrame([
    {
        "version": "sub_v008_catboost_alpha_pack",
        "dataset": "Full cleaned train",
        "features": "35 Alpha Pack",
        "rows": 19700,
        "cv_rmse": 0.23164778640435246,
        "cv_mae": 0.17673736118136243,
        "cv_r2": 0.03463008143352864,
        "prediction_std": 0.042242,
        "public_score": 0.38308
    },
    {
        "version": "sub_v010_catboost_alpha_pack_dropmissing",
        "dataset": "Drop missing train",
        "features": "35 Alpha Pack",
        "rows": 15518,
        "cv_rmse": 0.23180475883494558,
        "cv_mae": 0.17660570642311946,
        "cv_r2": 0.04023286825885215,
        "prediction_std": 0.044751843087494254,
        "public_score": 0.38176
    },
    {
        "version": "sub_v012_catboost_full_plus_alpha_dropmissing",
        "dataset": "Drop missing train",
        "features": "Full + Alpha, 70 features",
        "rows": 15518,
        "cv_rmse": 0.2319484336072119,
        "cv_mae": 0.17671839229429026,
        "cv_r2": 0.03904856170750963,
        "prediction_std": 0.04360086243404623,
        "public_score": None
    },
    {
        "version": "sub_v013_catboost_corr_guided_dropmissing",
        "dataset": "Drop missing train",
        "features": f"Correlation-guided, {len(v013_features)} features",
        "rows": len(train),
        "cv_rmse": np.mean(rmse_scores),
        "cv_mae": np.mean(mae_scores),
        "cv_r2": np.mean(r2_scores),
        "prediction_std": v013_preds.std(),
        "public_score": None
    }
])

comparison["rmse_vs_best_public"] = comparison["cv_rmse"] - comparison.loc[1, "cv_rmse"]
comparison["mae_vs_best_public"] = comparison["cv_mae"] - comparison.loc[1, "cv_mae"]
comparison["r2_vs_best_public"] = comparison["cv_r2"] - comparison.loc[1, "cv_r2"]
comparison["pred_std_vs_best_public"] = comparison["prediction_std"] - comparison.loc[1, "prediction_std"]

os.makedirs("../reports", exist_ok=True)

comparison.to_csv(
    "../reports/catboost_v013_corr_guided_comparison.csv",
    index=False
)

print("\nComparison with previous versions:")
display(comparison)

Train path: ../MLOpsedian/data/processed/train_dropmissing.csv
Test path: ../MLOpsedian/data/processed/test_dropmissing.csv
Train shape: (15518, 69)
Test shape: (5300, 68)
Train missing: 0
Test missing: 0
Duplicate train IDs: 0
Duplicate test IDs: 0
Train-only columns: {'flood_risk_score'}
Test-only columns: set()
Target valid: True

After feature engineering:
Train shape: (15518, 73)
Test shape: (5300, 72)
Train missing: 0
Test missing: 0

Feature check:
Number of V013 features: 49
Missing train features: []
Missing test features: []

Model data:
X shape: (15518, 49)
y shape: (15518,)
X_test shape: (5300, 49)
Missing in X: 0
Missing in X_test: 0
Feature columns match: True

Categorical features:
Number of categorical features: 11
['district', 'generation_date', 'reason_not_good_to_live', 'road_quality', 'landcover', 'place_name', 'water_supply', 'water_presence_flag', 'flood_occurrence_current_event', 'soil_type', 'is_good_to_live']

Target bin distribution:
flood_risk_score
0    1899
1    3455
2    5993
3    2655
4    1516
Name: count, dtype: int64

======================================================================
Fold 1
0:	learn: 0.2364775	test: 0.2361234	best: 0.2361234 (0)	total: 22.2ms	remaining: 44.4s
200:	learn: 0.2273908	test: 0.2315768	best: 0.2315668 (193)	total: 1.82s	remaining: 16.3s
400:	learn: 0.2222293	test: 0.2318110	best: 0.2315220 (227)	total: 3.78s	remaining: 15.1s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2315220252
bestIteration = 227

Shrink model to first 228 iterations.
Fold RMSE: 0.2315220254225369
Fold MAE : 0.1763257997443216
Fold R²  : 0.040040105291048955

======================================================================
Fold 2
0:	learn: 0.2367473	test: 0.2350747	best: 0.2350747 (0)	total: 8.68ms	remaining: 17.3s
200:	learn: 0.2270675	test: 0.2305175	best: 0.2305099 (196)	total: 2.65s	remaining: 23.8s
400:	learn: 0.2219421	test: 0.2303078	best: 0.2303078 (400)	total: 5.44s	remaining: 21.7s
600:	learn: 0.2165414	test: 0.2304376	best: 0.2302750 (436)	total: 8.25s	remaining: 19.2s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2302749502
bestIteration = 436

Shrink model to first 437 iterations.
Fold RMSE: 0.23027495054034616
Fold MAE : 0.17517177155853716
Fold R²  : 0.041821783888959296

======================================================================
Fold 3
0:	learn: 0.2367847	test: 0.2350884	best: 0.2350884 (0)	total: 7.39ms	remaining: 14.8s
200:	learn: 0.2276094	test: 0.2306052	best: 0.2305697 (138)	total: 2.85s	remaining: 25.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2305696755
bestIteration = 138

Shrink model to first 139 iterations.
Fold RMSE: 0.23056967543109746
Fold MAE : 0.17601435680732855
Fold R²  : 0.039492437631067356

======================================================================
Fold 4
0:	learn: 0.2360221	test: 0.2379545	best: 0.2379545 (0)	total: 9.88ms	remaining: 19.7s
200:	learn: 0.2264653	test: 0.2337687	best: 0.2337438 (191)	total: 2.77s	remaining: 24.8s
400:	learn: 0.2214650	test: 0.2337530	best: 0.2336393 (333)	total: 5.53s	remaining: 22s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2336392525
bestIteration = 333

Shrink model to first 334 iterations.
Fold RMSE: 0.23363925273330804
Fold MAE : 0.17755245640500536
Fold R²  : 0.037502079870809224

======================================================================
Fold 5
0:	learn: 0.2360174	test: 0.2379478	best: 0.2379478 (0)	total: 9.69ms	remaining: 19.4s
200:	learn: 0.2269487	test: 0.2334240	best: 0.2334229 (199)	total: 2.71s	remaining: 24.2s
400:	learn: 0.2221945	test: 0.2333506	best: 0.2333506 (400)	total: 5.44s	remaining: 21.7s
600:	learn: 0.2170635	test: 0.2334531	best: 0.2333218 (422)	total: 8.2s	remaining: 19.1s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2333218485
bestIteration = 422

Shrink model to first 423 iterations.
Fold RMSE: 0.23332184837261485
Fold MAE : 0.1785380498722371
Fold R²  : 0.03982265247971706

======================================================================
V013 Correlation-Guided CatBoost CV Results
Average RMSE: 0.2318655504999807
Average MAE : 0.17672048687748595
Average R²  : 0.039735811832320375

Prediction distribution:
Prediction min: 0.3745261242716835
Prediction max: 0.6232088306237765
Prediction mean: 0.4792686354170164
Prediction std: 0.043628823741673914

Submission shape: (5300, 2)
  record_id  flood_risk_score
0   F104559          0.474461
1   F100765          0.452572
2   F107573          0.472816
3   F110345          0.557893
4   F118850          0.509635

Missing values:
record_id           0
flood_risk_score    0
dtype: int64

Prediction range:
Min: 0.3745261242716835
Max: 0.6232088306237765

Submission is valid.

Saved: ../submissions/sub_v013_catboost_corr_guided_dropmissing.csv

Comparison with previous versions:

,version,dataset,features,rows,cv_rmse,cv_mae,cv_r2,prediction_std,public_score,rmse_vs_best_public,mae_vs_best_public,r2_vs_best_public,pred_std_vs_best_public
0,sub_v008_catboost_alpha_pack,Full cleaned train,35 Alpha Pack,19700,0.231648,0.176737,0.034630,0.042242,0.38308,-0.000157,0.000132,-0.005603,-0.002510
1,sub_v010_catboost_alpha_pack_dropmissing,Drop missing train,35 Alpha Pack,15518,0.231805,0.176606,0.040233,0.044752,0.38176,0.000000,0.000000,0.000000,0.000000
2,sub_v012_catboost_full_plus_alpha_dropmissing,Drop missing train,"Full + Alpha, 70 features",15518,0.231948,0.176718,0.039049,0.043601,NaN,0.000144,0.000113,-0.001184,-0.001151
3,sub_v013_catboost_corr_guided_dropmissing,Drop missing train,"Correlation-guided, 49 features",15518,0.231866,0.176720,0.039736,0.043629,NaN,0.000061,0.000115,-0.000497,-0.001123

In [7]:
# ============================================================
# V014: CatBoost Alpha Pack Drop-Missing Seed Ensemble
# Uses the proven V010 setup + multiple random seeds
# ============================================================

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from catboost import CatBoostRegressor

# ============================================================
# 1. Load best dataset: drop-missing
# ============================================================

train_path = "../data/processed/train_dropmissing.csv"
test_path = "../data/processed/test_dropmissing.csv"

if not os.path.exists(train_path):
    train_path = "../MLOpsedian/data/processed/train_dropmissing.csv"
    test_path = "../MLOpsedian/data/processed/test_dropmissing.csv"

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

id_col = "record_id"
target = "flood_risk_score"

print("Train path:", train_path)
print("Test path:", test_path)
print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Train missing:", train.isnull().sum().sum())
print("Test missing:", test.isnull().sum().sum())
print("Duplicate train IDs:", train[id_col].duplicated().sum())
print("Duplicate test IDs:", test[id_col].duplicated().sum())
print("Train-only columns:", set(train.columns) - set(test.columns))
print("Test-only columns:", set(test.columns) - set(train.columns))
print("Target valid:", train[target].between(0, 1).all())

# ============================================================
# 2. Add Alpha Pack engineered features
# ============================================================

def add_alpha_pack_features(df):
    df = df.copy()
    eps = 1e-5
    
    if "distance_to_river_m_clipped" in df.columns:
        distance = df["distance_to_river_m_clipped"]
    else:
        distance = df["distance_to_river_m"].clip(lower=0)
    
    if "rainfall_7d_mm_clipped" in df.columns:
        rainfall_7d = df["rainfall_7d_mm_clipped"]
    else:
        rainfall_7d = df["rainfall_7d_mm"].clip(lower=0)
    
    inundation = df["inundation_area_sqm"].clip(lower=0)
    
    df["GOLDEN_distance_rainfall_ratio"] = (
        np.log1p(distance) - np.log1p(rainfall_7d + eps)
    )
    
    df["distance_to_river_DIV_inundation_area"] = (
        distance / (inundation + eps)
    )
    
    df["distance_to_river_DIV_rainfall_7d"] = (
        distance / (rainfall_7d + eps)
    )
    
    df["rainfall_7d_MULT_inundation_area"] = (
        rainfall_7d * inundation
    )
    
    new_cols = [
        "GOLDEN_distance_rainfall_ratio",
        "distance_to_river_DIV_inundation_area",
        "distance_to_river_DIV_rainfall_7d",
        "rainfall_7d_MULT_inundation_area"
    ]
    
    for col in new_cols:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
        df[col] = df[col].fillna(df[col].median())
    
    return df

train_fe = add_alpha_pack_features(train)
test_fe = add_alpha_pack_features(test)

print("\nAfter feature engineering:")
print("Train shape:", train_fe.shape)
print("Test shape:", test_fe.shape)
print("Train missing:", train_fe.isnull().sum().sum())
print("Test missing:", test_fe.isnull().sum().sum())

# ============================================================
# 3. Use exact V010 Alpha Pack feature set
# ============================================================

alpha_pack_features = [
    "district",
    "distance_to_river_DIV_inundation_area",
    "distance_to_river_DIV_rainfall_7d",
    "GOLDEN_distance_rainfall_ratio",
    "generation_date",
    "reason_not_good_to_live",
    "inundation_area_sqm",
    "infrastructure_score",
    "extreme_weather_index",
    "terrain_roughness_index",
    "road_quality",
    "monthly_rainfall_mm_log1p",
    "landcover",
    "rainfall_7d_MULT_inundation_area",
    "place_name",
    "rainfall_7d_mm",
    "seasonal_index",
    "ndwi_qmap",
    "latitude",
    "longitude",
    "distance_to_river_m",
    "ndwi",
    "water_supply",
    "nearest_evac_km_log1p",
    "elevation_m_yeojohnson",
    "monthly_rainfall_mm",
    "socioeconomic_status_index",
    "population_density_per_km2_log1p",
    "water_presence_flag",
    "nearest_hospital_km_log1p",
    "ndvi_qmap",
    "flood_occurrence_current_event",
    "rainfall_7d_mm_log1p",
    "soil_type",
    "population_density_per_km2"
]

missing_train_features = [col for col in alpha_pack_features if col not in train_fe.columns]
missing_test_features = [col for col in alpha_pack_features if col not in test_fe.columns]

print("\nFeature check:")
print("Number of Alpha Pack features:", len(alpha_pack_features))
print("Missing train features:", missing_train_features)
print("Missing test features:", missing_test_features)

if len(missing_train_features) > 0 or len(missing_test_features) > 0:
    raise ValueError("Some Alpha Pack features are missing. Stop and check columns.")

# ============================================================
# 4. Prepare model data
# ============================================================

X = train_fe[alpha_pack_features].copy()
y = train_fe[target].copy()

X_test = test_fe[alpha_pack_features].copy()
test_ids = test_fe[id_col].copy()

print("\nModel data:")
print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)
print("Missing in X:", X.isnull().sum().sum())
print("Missing in X_test:", X_test.isnull().sum().sum())
print("Feature columns match:", list(X.columns) == list(X_test.columns))

cat_features = [
    col for col in X.columns
    if X[col].dtype == "object" or str(X[col].dtype) == "str"
]

print("\nCategorical features:")
print("Number of categorical features:", len(cat_features))
print(cat_features)

# ============================================================
# 5. Target bins for balance-aware folds
# ============================================================

target_bins = pd.cut(
    y,
    bins=[-0.001, 0.2, 0.4, 0.6, 0.8, 1.001],
    labels=[0, 1, 2, 3, 4]
)

print("\nTarget bin distribution:")
print(target_bins.value_counts().sort_index())

# ============================================================
# 6. Submission validation function
# ============================================================

def validate_submission(submission):
    print("\nSubmission shape:", submission.shape)
    print(submission.head())
    
    print("\nMissing values:")
    print(submission.isnull().sum())
    
    print("\nPrediction range:")
    print("Min:", submission["flood_risk_score"].min())
    print("Max:", submission["flood_risk_score"].max())
    
    assert submission.shape[0] == len(test_ids)
    assert list(submission.columns) == ["record_id", "flood_risk_score"]
    assert submission["flood_risk_score"].isnull().sum() == 0
    assert submission["flood_risk_score"].between(0, 1).all()
    
    print("\nSubmission is valid.")

# ============================================================
# 7. Seed ensemble training
# ============================================================

seeds = [42, 202, 777, 2026, 9999]
n_splits = 5

all_seed_oof_preds = []
all_seed_test_preds = []
seed_score_rows = []

for seed in seeds:
    print("\n" + "#" * 80)
    print(f"Training seed: {seed}")
    print("#" * 80)
    
    skf = StratifiedKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=seed
    )
    
    seed_oof_preds = np.zeros(len(X))
    seed_test_preds = np.zeros(len(X_test))
    
    fold_rmse_scores = []
    fold_mae_scores = []
    fold_r2_scores = []
    
    for fold, (train_idx, valid_idx) in enumerate(skf.split(X, target_bins), 1):
        print("\n" + "=" * 70)
        print(f"Seed {seed} | Fold {fold}")
        
        X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
        y_train, y_valid = y.iloc[train_idx], y.iloc[valid_idx]
        
        model = CatBoostRegressor(
            iterations=2000,
            learning_rate=0.03,
            depth=6,
            loss_function="RMSE",
            eval_metric="RMSE",
            random_seed=seed + fold,
            verbose=300,
            early_stopping_rounds=200,
            allow_writing_files=False
        )
        
        model.fit(
            X_train,
            y_train,
            cat_features=cat_features,
            eval_set=(X_valid, y_valid),
            use_best_model=True
        )
        
        valid_preds = model.predict(X_valid)
        valid_preds = np.clip(valid_preds, 0, 1)
        
        seed_oof_preds[valid_idx] = valid_preds
        
        rmse = np.sqrt(mean_squared_error(y_valid, valid_preds))
        mae = mean_absolute_error(y_valid, valid_preds)
        r2 = r2_score(y_valid, valid_preds)
        
        fold_rmse_scores.append(rmse)
        fold_mae_scores.append(mae)
        fold_r2_scores.append(r2)
        
        print("Fold RMSE:", rmse)
        print("Fold MAE :", mae)
        print("Fold R²  :", r2)
        
        fold_test_preds = model.predict(X_test)
        seed_test_preds += fold_test_preds / n_splits
    
    seed_oof_preds = np.clip(seed_oof_preds, 0, 1)
    seed_test_preds = np.clip(seed_test_preds, 0, 1)
    
    seed_rmse = np.sqrt(mean_squared_error(y, seed_oof_preds))
    seed_mae = mean_absolute_error(y, seed_oof_preds)
    seed_r2 = r2_score(y, seed_oof_preds)
    
    print("\nSeed summary:")
    print("Seed:", seed)
    print("OOF RMSE:", seed_rmse)
    print("OOF MAE :", seed_mae)
    print("OOF R²  :", seed_r2)
    print("Test pred std:", seed_test_preds.std())
    
    seed_score_rows.append({
        "seed": seed,
        "oof_rmse": seed_rmse,
        "oof_mae": seed_mae,
        "oof_r2": seed_r2,
        "test_pred_min": seed_test_preds.min(),
        "test_pred_max": seed_test_preds.max(),
        "test_pred_mean": seed_test_preds.mean(),
        "test_pred_std": seed_test_preds.std()
    })
    
    all_seed_oof_preds.append(seed_oof_preds)
    all_seed_test_preds.append(seed_test_preds)

# ============================================================
# 8. Average predictions across seeds
# ============================================================

ensemble_oof_preds = np.mean(all_seed_oof_preds, axis=0)
ensemble_test_preds = np.mean(all_seed_test_preds, axis=0)

ensemble_oof_preds = np.clip(ensemble_oof_preds, 0, 1)
ensemble_test_preds = np.clip(ensemble_test_preds, 0, 1)

ensemble_rmse = np.sqrt(mean_squared_error(y, ensemble_oof_preds))
ensemble_mae = mean_absolute_error(y, ensemble_oof_preds)
ensemble_r2 = r2_score(y, ensemble_oof_preds)

print("\n" + "#" * 80)
print("V014 Seed Ensemble Results")
print("#" * 80)
print("Ensemble OOF RMSE:", ensemble_rmse)
print("Ensemble OOF MAE :", ensemble_mae)
print("Ensemble OOF R²  :", ensemble_r2)

print("\nPrediction distribution:")
print("Prediction min:", ensemble_test_preds.min())
print("Prediction max:", ensemble_test_preds.max())
print("Prediction mean:", ensemble_test_preds.mean())
print("Prediction std:", ensemble_test_preds.std())

# ============================================================
# 9. Create submission
# ============================================================

sub_v014 = pd.DataFrame({
    "record_id": test_ids,
    "flood_risk_score": ensemble_test_preds
})

validate_submission(sub_v014)

os.makedirs("../submissions", exist_ok=True)

sub_v014.to_csv(
    "../submissions/sub_v014_catboost_alpha_pack_dropmissing_seed_ensemble.csv",
    index=False
)

print("\nSaved: ../submissions/sub_v014_catboost_alpha_pack_dropmissing_seed_ensemble.csv")

# ============================================================
# 10. Save comparison reports
# ============================================================

seed_scores_df = pd.DataFrame(seed_score_rows)

comparison = pd.DataFrame([
    {
        "version": "sub_v010_catboost_alpha_pack_dropmissing",
        "model": "Single CatBoost Alpha Pack Drop-Missing",
        "rows": 15518,
        "features": "35 Alpha Pack",
        "cv_rmse": 0.23180475883494558,
        "cv_mae": 0.17660570642311946,
        "cv_r2": 0.04023286825885215,
        "prediction_std": 0.044751843087494254,
        "public_score": 0.38176
    },
    {
        "version": "sub_v014_catboost_alpha_pack_dropmissing_seed_ensemble",
        "model": f"Seed Ensemble CatBoost, seeds={seeds}",
        "rows": len(train),
        "features": "35 Alpha Pack",
        "cv_rmse": ensemble_rmse,
        "cv_mae": ensemble_mae,
        "cv_r2": ensemble_r2,
        "prediction_std": ensemble_test_preds.std(),
        "public_score": None
    }
])

comparison["rmse_vs_v010"] = comparison["cv_rmse"] - comparison.loc[0, "cv_rmse"]
comparison["mae_vs_v010"] = comparison["cv_mae"] - comparison.loc[0, "cv_mae"]
comparison["r2_vs_v010"] = comparison["cv_r2"] - comparison.loc[0, "cv_r2"]
comparison["pred_std_vs_v010"] = comparison["prediction_std"] - comparison.loc[0, "prediction_std"]

os.makedirs("../reports", exist_ok=True)

seed_scores_df.to_csv(
    "../reports/v014_seed_scores.csv",
    index=False
)

comparison.to_csv(
    "../reports/v014_seed_ensemble_comparison.csv",
    index=False
)

print("\nSeed-level scores:")
display(seed_scores_df)

print("\nComparison with V010:")
display(comparison)

Train path: ../MLOpsedian/data/processed/train_dropmissing.csv
Test path: ../MLOpsedian/data/processed/test_dropmissing.csv
Train shape: (15518, 69)
Test shape: (5300, 68)
Train missing: 0
Test missing: 0
Duplicate train IDs: 0
Duplicate test IDs: 0
Train-only columns: {'flood_risk_score'}
Test-only columns: set()
Target valid: True

After feature engineering:
Train shape: (15518, 73)
Test shape: (5300, 72)
Train missing: 0
Test missing: 0

Feature check:
Number of Alpha Pack features: 35
Missing train features: []
Missing test features: []

Model data:
X shape: (15518, 35)
y shape: (15518,)
X_test shape: (5300, 35)
Missing in X: 0
Missing in X_test: 0
Feature columns match: True

Categorical features:
Number of categorical features: 10
['district', 'generation_date', 'reason_not_good_to_live', 'road_quality', 'landcover', 'place_name', 'water_supply', 'water_presence_flag', 'flood_occurrence_current_event', 'soil_type']

Target bin distribution:
flood_risk_score
0    1899
1    3455
2    5993
3    2655
4    1516
Name: count, dtype: int64

################################################################################
Training seed: 42
################################################################################

======================================================================
Seed 42 | Fold 1
0:	learn: 0.2364969	test: 0.2360924	best: 0.2360924 (0)	total: 24.3ms	remaining: 48.6s
300:	learn: 0.2255166	test: 0.2317478	best: 0.2317092 (271)	total: 2.59s	remaining: 14.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2316819405
bestIteration = 351

Shrink model to first 352 iterations.
Fold RMSE: 0.23168194068370526
Fold MAE : 0.17632492961934465
Fold R²  : 0.038713533847676174

======================================================================
Seed 42 | Fold 2
0:	learn: 0.2367391	test: 0.2350707	best: 0.2350707 (0)	total: 9.25ms	remaining: 18.5s
300:	learn: 0.2254899	test: 0.2303922	best: 0.2303872 (299)	total: 3.75s	remaining: 21.2s
600:	learn: 0.2174353	test: 0.2303459	best: 0.2302005 (420)	total: 8.12s	remaining: 18.9s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2302004942
bestIteration = 420

Shrink model to first 421 iterations.
Fold RMSE: 0.23020049457971475
Fold MAE : 0.1750286484506056
Fold R²  : 0.042441308901750685

======================================================================
Seed 42 | Fold 3
0:	learn: 0.2367448	test: 0.2350777	best: 0.2350777 (0)	total: 8.8ms	remaining: 17.6s
300:	learn: 0.2254952	test: 0.2307544	best: 0.2306751 (155)	total: 4.09s	remaining: 23.1s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2306750845
bestIteration = 155

Shrink model to first 156 iterations.
Fold RMSE: 0.23067508452663343
Fold MAE : 0.17605041651151615
Fold R²  : 0.03861401008860399

======================================================================
Seed 42 | Fold 4
0:	learn: 0.2360616	test: 0.2380016	best: 0.2380016 (0)	total: 7.98ms	remaining: 15.9s
300:	learn: 0.2247134	test: 0.2336886	best: 0.2336508 (240)	total: 3.63s	remaining: 20.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.233531603
bestIteration = 355

Shrink model to first 356 iterations.
Fold RMSE: 0.23353160319073427
Fold MAE : 0.17716696509459645
Fold R²  : 0.038388819490463244

======================================================================
Seed 42 | Fold 5
0:	learn: 0.2360503	test: 0.2379286	best: 0.2379286 (0)	total: 9.05ms	remaining: 18.1s
300:	learn: 0.2252126	test: 0.2331000	best: 0.2330975 (298)	total: 3.77s	remaining: 21.3s
600:	learn: 0.2176147	test: 0.2330573	best: 0.2329347 (480)	total: 7.64s	remaining: 17.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2329346713
bestIteration = 480

Shrink model to first 481 iterations.
Fold RMSE: 0.2329346711939401
Fold MAE : 0.17845757243953456
Fold R²  : 0.04300666896576666

Seed summary:
Seed: 42
OOF RMSE: 0.2318080790811201
OOF MAE : 0.17660555091824204
OOF R²  : 0.04023513228302855
Test pred std: 0.044751843087494254

################################################################################
Training seed: 202
################################################################################

======================================================================
Seed 202 | Fold 1
0:	learn: 0.2363855	test: 0.2364590	best: 0.2364590 (0)	total: 8.19ms	remaining: 16.4s
300:	learn: 0.2256747	test: 0.2313110	best: 0.2313009 (256)	total: 3.59s	remaining: 20.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2312858602
bestIteration = 308

Shrink model to first 309 iterations.
Fold RMSE: 0.23128586044611146
Fold MAE : 0.17595772135758636
Fold R²  : 0.04495121283369363

======================================================================
Seed 202 | Fold 2
0:	learn: 0.2363479	test: 0.2366589	best: 0.2366589 (0)	total: 8.59ms	remaining: 17.2s
300:	learn: 0.2247362	test: 0.2333083	best: 0.2331287 (176)	total: 3.74s	remaining: 21.1s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2331287324
bestIteration = 176

Shrink model to first 177 iterations.
Fold RMSE: 0.23312873240671114
Fold MAE : 0.17731943685368223
Fold R²  : 0.03082405799141985

======================================================================
Seed 202 | Fold 3
0:	learn: 0.2365982	test: 0.2357971	best: 0.2357971 (0)	total: 9.21ms	remaining: 18.4s
300:	learn: 0.2249900	test: 0.2313260	best: 0.2313260 (300)	total: 3.78s	remaining: 21.3s
600:	learn: 0.2165774	test: 0.2314386	best: 0.2312810 (430)	total: 7.58s	remaining: 17.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2312809819
bestIteration = 430

Shrink model to first 431 iterations.
Fold RMSE: 0.23128098219549473
Fold MAE : 0.17626855095837224
Fold R²  : 0.03904154905616619

======================================================================
Seed 202 | Fold 4
0:	learn: 0.2362322	test: 0.2373785	best: 0.2373785 (0)	total: 9.39ms	remaining: 18.8s
300:	learn: 0.2256563	test: 0.2322578	best: 0.2322448 (262)	total: 3.65s	remaining: 20.6s
600:	learn: 0.2188840	test: 0.2320680	best: 0.2320517 (514)	total: 7.5s	remaining: 17.5s
900:	learn: 0.2121889	test: 0.2320500	best: 0.2319871 (728)	total: 12.1s	remaining: 14.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2319870524
bestIteration = 728

Shrink model to first 729 iterations.
Fold RMSE: 0.231987052476171
Fold MAE : 0.17771766304290504
Fold R²  : 0.046185860799529244

======================================================================
Seed 202 | Fold 5
0:	learn: 0.2365311	test: 0.2359266	best: 0.2359266 (0)	total: 8.04ms	remaining: 16.1s
300:	learn: 0.2255656	test: 0.2313402	best: 0.2313311 (259)	total: 5.14s	remaining: 29s
600:	learn: 0.2171932	test: 0.2311819	best: 0.2310646 (448)	total: 10.2s	remaining: 23.7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2310645779
bestIteration = 448

Shrink model to first 449 iterations.
Fold RMSE: 0.2310645779391089
Fold MAE : 0.1767846228946103
Fold R²  : 0.04243288238381637

Seed summary:
Seed: 202
OOF RMSE: 0.23175070508161943
OOF MAE : 0.1768095421141046
OOF R²  : 0.04071016951830997
Test pred std: 0.04421104700523078

################################################################################
Training seed: 777
################################################################################

======================================================================
Seed 777 | Fold 1
0:	learn: 0.2366384	test: 0.2354850	best: 0.2354850 (0)	total: 8.78ms	remaining: 17.5s
300:	learn: 0.2260180	test: 0.2307051	best: 0.2306652 (240)	total: 4.67s	remaining: 26.4s
600:	learn: 0.2185051	test: 0.2304579	best: 0.2304160 (586)	total: 9.04s	remaining: 21s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2304160137
bestIteration = 586

Shrink model to first 587 iterations.
Fold RMSE: 0.23041601372560339
Fold MAE : 0.17515754501714198
Fold R²  : 0.04396279978883466

======================================================================
Seed 777 | Fold 2
0:	learn: 0.2363688	test: 0.2367942	best: 0.2367942 (0)	total: 11ms	remaining: 22s
300:	learn: 0.2252199	test: 0.2317940	best: 0.2317435 (279)	total: 4.49s	remaining: 25.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2317032556
bestIteration = 371

Shrink model to first 372 iterations.
Fold RMSE: 0.23170325555488852
Fold MAE : 0.17668876137958975
Fold R²  : 0.043977392918638336

======================================================================
Seed 777 | Fold 3
0:	learn: 0.2363794	test: 0.2366353	best: 0.2366353 (0)	total: 8.67ms	remaining: 17.3s
300:	learn: 0.2252168	test: 0.2308991	best: 0.2308991 (300)	total: 3.79s	remaining: 21.4s
600:	learn: 0.2177857	test: 0.2310531	best: 0.2308498 (415)	total: 7.94s	remaining: 18.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2308498202
bestIteration = 415

Shrink model to first 416 iterations.
Fold RMSE: 0.2308498205635452
Fold MAE : 0.17629426594355674
Fold R²  : 0.04976705771233114

======================================================================
Seed 777 | Fold 4
0:	learn: 0.2363558	test: 0.2365201	best: 0.2365201 (0)	total: 9.47ms	remaining: 18.9s
300:	learn: 0.2244433	test: 0.2333884	best: 0.2332602 (210)	total: 3.97s	remaining: 22.4s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2332601891
bestIteration = 210

Shrink model to first 211 iterations.
Fold RMSE: 0.2332601893414929
Fold MAE : 0.17747568359709628
Fold R²  : 0.028730971292146745

======================================================================
Seed 777 | Fold 5
0:	learn: 0.2363581	test: 0.2367790	best: 0.2367790 (0)	total: 7.3ms	remaining: 14.6s
300:	learn: 0.2253848	test: 0.2324079	best: 0.2323435 (240)	total: 3.96s	remaining: 22.4s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2323434926
bestIteration = 240

Shrink model to first 241 iterations.
Fold RMSE: 0.23234349273820618
Fold MAE : 0.1770971659990054
Fold R²  : 0.03849111543648598

Seed summary:
Seed: 777
OOF RMSE: 0.2317166663354137
OOF MAE : 0.17654258853208912
OOF R²  : 0.0409919432033925
Test pred std: 0.045169184057984306

################################################################################
Training seed: 2026
################################################################################

======================================================================
Seed 2026 | Fold 1
0:	learn: 0.2366939	test: 0.2352874	best: 0.2352874 (0)	total: 8.71ms	remaining: 17.4s
300:	learn: 0.2254910	test: 0.2298346	best: 0.2298346 (300)	total: 3.75s	remaining: 21.2s
600:	learn: 0.2177877	test: 0.2298039	best: 0.2297626 (563)	total: 7.98s	remaining: 18.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2297626182
bestIteration = 563

Shrink model to first 564 iterations.
Fold RMSE: 0.22976261843745371
Fold MAE : 0.17477183661279944
Fold R²  : 0.04794375572595844

======================================================================
Seed 2026 | Fold 2
0:	learn: 0.2365620	test: 0.2358001	best: 0.2358001 (0)	total: 8.97ms	remaining: 17.9s
300:	learn: 0.2247032	test: 0.2334128	best: 0.2331431 (120)	total: 3.93s	remaining: 22.2s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2331430832
bestIteration = 120

Shrink model to first 121 iterations.
Fold RMSE: 0.23314308350457996
Fold MAE : 0.17829164839634795
Fold R²  : 0.023408340904054636

======================================================================
Seed 2026 | Fold 3
0:	learn: 0.2360643	test: 0.2379725	best: 0.2379725 (0)	total: 10.1ms	remaining: 20.3s
300:	learn: 0.2251114	test: 0.2326864	best: 0.2326862 (299)	total: 4.18s	remaining: 23.6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2326480236
bestIteration = 321

Shrink model to first 322 iterations.
Fold RMSE: 0.23264802368233214
Fold MAE : 0.17818031277154936
Fold R²  : 0.04567499517656548

======================================================================
Seed 2026 | Fold 4
0:	learn: 0.2364387	test: 0.2365002	best: 0.2365002 (0)	total: 10.2ms	remaining: 20.4s
300:	learn: 0.2257011	test: 0.2318348	best: 0.2318194 (293)	total: 3.75s	remaining: 21.2s
600:	learn: 0.2182863	test: 0.2317495	best: 0.2317297 (417)	total: 7.6s	remaining: 17.7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.231729651
bestIteration = 417

Shrink model to first 418 iterations.
Fold RMSE: 0.23172965121040626
Fold MAE : 0.17610864559515485
Fold R²  : 0.04124805105953011

======================================================================
Seed 2026 | Fold 5
0:	learn: 0.2363563	test: 0.2367084	best: 0.2367084 (0)	total: 9.25ms	remaining: 18.5s
300:	learn: 0.2247460	test: 0.2325871	best: 0.2325871 (300)	total: 3.69s	remaining: 20.8s
600:	learn: 0.2172788	test: 0.2323420	best: 0.2322966 (557)	total: 7.49s	remaining: 17.4s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2322965762
bestIteration = 557

Shrink model to first 558 iterations.
Fold RMSE: 0.23229657613835378
Fold MAE : 0.17668848237736667
Fold R²  : 0.038109924176195076

Seed summary:
Seed: 2026
OOF RMSE: 0.23191893560995588
OOF MAE : 0.1768082379436794
OOF R²  : 0.039316944764780204
Test pred std: 0.04431486055112104

################################################################################
Training seed: 9999
################################################################################

======================================================================
Seed 9999 | Fold 1
0:	learn: 0.2359965	test: 0.2382271	best: 0.2382271 (0)	total: 9.89ms	remaining: 19.8s
300:	learn: 0.2251653	test: 0.2329697	best: 0.2329697 (300)	total: 3.78s	remaining: 21.3s
600:	learn: 0.2173840	test: 0.2331355	best: 0.2329085 (436)	total: 7.61s	remaining: 17.7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2329085388
bestIteration = 436

Shrink model to first 437 iterations.
Fold RMSE: 0.2329085387950089
Fold MAE : 0.17780499055664165
Fold R²  : 0.04561943836719573

======================================================================
Seed 9999 | Fold 2
0:	learn: 0.2365406	test: 0.2359244	best: 0.2359244 (0)	total: 8.2ms	remaining: 16.4s
300:	learn: 0.2258072	test: 0.2308396	best: 0.2308371 (299)	total: 3.75s	remaining: 21.2s
600:	learn: 0.2195318	test: 0.2308205	best: 0.2306966 (544)	total: 7.65s	remaining: 17.8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2306966414
bestIteration = 544

Shrink model to first 545 iterations.
Fold RMSE: 0.23069664148742874
Fold MAE : 0.17567774124359753
Fold R²  : 0.045385762165710886

======================================================================
Seed 9999 | Fold 3
0:	learn: 0.2365275	test: 0.2360207	best: 0.2360207 (0)	total: 8.94ms	remaining: 17.9s
300:	learn: 0.2251369	test: 0.2316477	best: 0.2316019 (242)	total: 3.64s	remaining: 20.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2315675927
bestIteration = 334

Shrink model to first 335 iterations.
Fold RMSE: 0.23156759267156268
Fold MAE : 0.1756858493101875
Fold R²  : 0.03880651475727048

======================================================================
Seed 9999 | Fold 4
0:	learn: 0.2361937	test: 0.2374288	best: 0.2374288 (0)	total: 11ms	remaining: 21.9s
300:	learn: 0.2245916	test: 0.2330277	best: 0.2329994 (233)	total: 3.72s	remaining: 21s
600:	learn: 0.2175818	test: 0.2331052	best: 0.2329706 (437)	total: 7.52s	remaining: 17.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2329706376
bestIteration = 437

Shrink model to first 438 iterations.
Fold RMSE: 0.2329706379120361
Fold MAE : 0.17816000373284113
Fold R²  : 0.0384671884329848

======================================================================
Seed 9999 | Fold 5
0:	learn: 0.2368919	test: 0.2346054	best: 0.2346054 (0)	total: 9.15ms	remaining: 18.3s
300:	learn: 0.2250849	test: 0.2311318	best: 0.2310471 (235)	total: 3.77s	remaining: 21.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.2310471181
bestIteration = 235

Shrink model to first 236 iterations.
Fold RMSE: 0.2310471184724444
Fold MAE : 0.17651324240128288
Fold R²  : 0.031237645592215646

Seed summary:
Seed: 9999
OOF RMSE: 0.2318399947489623
OOF MAE : 0.17676829221039772
OOF R²  : 0.0399708304904165
Test pred std: 0.04506322009515229

################################################################################
V014 Seed Ensemble Results
################################################################################
Ensemble OOF RMSE: 0.23157158780580725
Ensemble OOF MAE : 0.17641904594511257
Ensemble OOF R²  : 0.04219244315562676

Prediction distribution:
Prediction min: 0.3642316667609831
Prediction max: 0.6413987232314529
Prediction mean: 0.4787833620514453
Prediction std: 0.04458173599051368

Submission shape: (5300, 2)
  record_id  flood_risk_score
0   F104559          0.466573
1   F100765          0.447645
2   F107573          0.472267
3   F110345          0.556143
4   F118850          0.517290

Missing values:
record_id           0
flood_risk_score    0
dtype: int64

Prediction range:
Min: 0.3642316667609831
Max: 0.6413987232314529

Submission is valid.

Saved: ../submissions/sub_v014_catboost_alpha_pack_dropmissing_seed_ensemble.csv

Seed-level scores:

,seed,oof_rmse,oof_mae,oof_r2,test_pred_min,test_pred_max,test_pred_mean,test_pred_std
0,42,0.231808,0.176606,0.040235,0.367827,0.632363,0.479113,0.044752
1,202,0.231751,0.176810,0.040710,0.364201,0.642449,0.480106,0.044211
2,777,0.231717,0.176543,0.040992,0.362635,0.642047,0.477864,0.045169
3,2026,0.231919,0.176808,0.039317,0.361560,0.640691,0.478067,0.044315
4,9999,0.231840,0.176768,0.039971,0.364934,0.649443,0.478767,0.045063

Comparison with V010:

,version,model,rows,features,cv_rmse,cv_mae,cv_r2,prediction_std,public_score,rmse_vs_v010,mae_vs_v010,r2_vs_v010,pred_std_vs_v010
0,sub_v010_catboost_alpha_pack_dropmissing,Single CatBoost Alpha Pack Drop-Missing,15518,35 Alpha Pack,0.231805,0.176606,0.040233,0.044752,0.38176,0.000000,0.000000,0.00000,0.00000
1,sub_v014_catboost_alpha_pack_dropmissing_seed_...,"Seed Ensemble CatBoost, seeds=[42, 202, 777, 2...",15518,35 Alpha Pack,0.231572,0.176419,0.042192,0.044582,NaN,-0.000233,-0.000187,0.00196,-0.00017